import { supabase } from './auth-client.js';

const FUNCTION_BASE='https://afhnfnfbqdqqzrghovfc.supabase.co/functions/v1/ms-parcel-api';
const PUBLISHABLE_KEY='sb_publishable_4GStzbYK3_BhthidusT_hw_DqtzC7qE';
const $=(id)=>document.getElementById(id);
const esc=(v)=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const state={admin:false,branchId:0,branches:[],users:[]};

async function api(route,options={}){const{data}=await supabase.auth.getSession();const token=data?.session?.access_token;if(!token)throw new Error('กรุณาเข้าสู่ระบบ');const headers=new Headers(options.headers||{});headers.set('Authorization',`Bearer ${token}`);headers.set('apikey',PUBLISHABLE_KEY);if(options.body&&!headers.has('Content-Type'))headers.set('Content-Type','application/json');const res=await fetch(`${FUNCTION_BASE}/${route}`,{...options,headers});const out=await res.json().catch(()=>({ok:false,message:`HTTP ${res.status}`}));if(!res.ok||out.ok===false)throw new Error(out.message||`HTTP ${res.status}`);return out;}
function branchName(id){const b=state.branches.find(x=>Number(x.id)===Number(id));return b?`${b.code} · ${b.name}`:`#${id}`;}
function accessFor(user,branchId){return(Array.isArray(user?.branch_access)?user.branch_access:[]).find(a=>Number(a.branch_id)===Number(branchId))||null;}
function hideLegacyAdmin(){['manage-users-btn','manage-branches-btn','nav-users-btn','nav-branches-btn'].forEach(id=>$(id)?.classList.add('admin-legacy-hidden'));}

function installUi(){
  if($('admin-control-btn'))return;
  const actions=document.querySelector('.topbar-actions');if(actions){const btn=document.createElement('button');btn.id='admin-control-btn';btn.type='button';btn.className='btn btn-header hidden';btn.textContent='หลังบ้าน';btn.addEventListener('click',()=>{$('admin-control-dialog').showModal();void loadAll();});actions.insertBefore(btn,$('upload-har-btn')||null);}
  const dialog=document.createElement('dialog');dialog.id='admin-control-dialog';dialog.innerHTML=`<div class="dialog-card admin-control-card"><button id="admin-control-close" class="dialog-close" type="button">×</button><div class="admin-control-head"><div><h2>ศูนย์จัดการระบบ</h2><p>ผู้ใช้ · หลาย HUB · Own HUB · สิทธิ์ HAR · สิทธิ์ตั้งกะ</p></div><button id="admin-refresh" class="btn btn-header" type="button">รีเฟรช</button></div><nav class="admin-tabs"><button class="admin-tab active" data-admin-tab="users" type="button">ผู้ใช้</button><button class="admin-tab" data-admin-tab="branches" type="button">HUB / สาขา</button><button class="admin-tab" data-admin-tab="health" type="button">สถานะระบบ</button></nav><section class="admin-pane" data-admin-pane="users"><form id="admin-create-user" class="admin-create-card"><h3>สร้างผู้ใช้</h3><div class="admin-form-fields"><label><span>Username</span><input id="acu-username" minlength="3" maxlength="32" required></label><label><span>ชื่อแสดง</span><input id="acu-display" maxlength="80"></label><label><span>รหัสผ่าน</span><input id="acu-password" type="password" minlength="6" maxlength="128" required></label><label><span>HUB เริ่มต้น</span><select id="acu-default"></select></label></div><div><strong class="admin-section-label">สิทธิ์ HUB</strong><div id="acu-access" class="access-matrix"></div></div><button class="btn btn-accent" type="submit">สร้างผู้ใช้</button></form><div id="admin-users-status" class="sync-text"></div><div id="admin-users-list" class="admin-user-list"></div></section><section class="admin-pane hidden" data-admin-pane="branches"><form id="admin-create-branch" class="admin-create-card"><h3>เพิ่ม HUB / สาขา</h3><div class="admin-form-fields"><label><span>รหัส</span><input id="acb-code" maxlength="20" required></label><label><span>ชื่อ</span><input id="acb-name" maxlength="120" required></label><label><span>Own HUB</span><input id="acb-own" maxlength="120" placeholder="เช่น 02 NE1"></label><label class="wide"><span>ชื่อเรียกอื่นของ HUB</span><input id="acb-alias" maxlength="400" placeholder="คั่นด้วย ,"></label></div><button class="btn btn-accent" type="submit">เพิ่ม HUB / สาขา</button></form><div id="admin-branches-status" class="sync-text"></div><div id="admin-branches-list" class="admin-branch-list"></div></section><section class="admin-pane hidden" data-admin-pane="health"><div id="admin-health-grid" class="admin-health-grid"></div><div class="admin-health-note">ข้อมูล Health หน้านี้ใช้สถานะ cache/connection ที่ระบบมีอยู่แล้ว ไม่สร้าง MS polling เพิ่ม</div></section></div>`;document.body.appendChild(dialog);
  $('admin-control-close').addEventListener('click',()=>dialog.close());$('admin-refresh').addEventListener('click',()=>void loadAll());$('admin-create-user').addEventListener('submit',createUser);$('admin-create-branch').addEventListener('submit',createBranch);
  document.querySelectorAll('.admin-tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.admin-tab').forEach(x=>x.classList.toggle('active',x===btn));document.querySelectorAll('[data-admin-pane]').forEach(p=>p.classList.toggle('hidden',p.dataset.adminPane!==btn.dataset.adminTab));}));
  hideLegacyAdmin();new MutationObserver(hideLegacyAdmin).observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});
}
function renderAccessMatrix(containerId,user=null){const el=$(containerId);if(!el)return;el.innerHTML=state.branches.map(b=>{const a=user?accessFor(user,b.id):null,checked=!!a;return`<label class="access-row" data-branch-id="${Number(b.id)}"><span class="access-branch"><input class="access-enabled" type="checkbox" ${checked?'checked':''}><b>${esc(b.code)}</b><small>${esc(b.name)}</small></span><span><input class="access-har" type="checkbox" ${a?.can_upload_har?'checked':''} ${checked?'':'disabled'}> HAR</span><span><input class="access-shift" type="checkbox" ${a?.can_manage_shift!==false&&checked?'checked':''} ${checked?'':'disabled'}> ตั้งกะ</span></label>`;}).join('')||'<div class="empty-state">ยังไม่มี HUB</div>';el.querySelectorAll('.access-row').forEach(row=>{const enabled=row.querySelector('.access-enabled'),sync=()=>row.querySelectorAll('.access-har,.access-shift').forEach(c=>c.disabled=!enabled.checked);enabled.addEventListener('change',sync);sync();});}
function collectAccess(root){return[...root.querySelectorAll('.access-row')].filter(row=>row.querySelector('.access-enabled')?.checked).map(row=>({branchId:Number(row.dataset.branchId),canUploadHar:!!row.querySelector('.access-har')?.checked,canManageShift:!!row.querySelector('.access-shift')?.checked}));}
function fillDefault(select,user=null){const current=Number(user?.branch_id||state.branchId||state.branches[0]?.id||0);select.innerHTML=state.branches.map(b=>`<option value="${Number(b.id)}" ${Number(b.id)===current?'selected':''}>${esc(b.code)} · ${esc(b.name)}</option>`).join('');}

async function loadAll(){if(!state.admin)return;await Promise.allSettled([loadUsers(),loadBranches()]);renderHealth();}
async function loadUsers(){try{$('admin-users-status').textContent='กำลังอ่านผู้ใช้…';const out=await api('users');state.users=out.data?.users||[];state.branches=out.data?.branches||state.branches;fillDefault($('acu-default'));renderAccessMatrix('acu-access');renderUsers();$('admin-users-status').textContent=`${state.users.length} บัญชี · ${state.branches.length} HUB/สาขา`;}catch(e){$('admin-users-status').textContent=`โหลดผู้ใช้ไม่สำเร็จ: ${e.message}`;}}
async function loadBranches(){try{$('admin-branches-status').textContent='กำลังอ่าน HUB…';const out=await api('branches');state.branches=out.data?.branches||[];renderBranches();$('admin-branches-status').textContent=`${state.branches.length} HUB/สาขา`;if($('acu-default')){fillDefault($('acu-default'));renderAccessMatrix('acu-access');}}catch(e){$('admin-branches-status').textContent=`โหลด HUB ไม่สำเร็จ: ${e.message}`;}}
function renderUsers(){$('admin-users-list').innerHTML=state.users.map(u=>{if(u.role==='admin')return`<article class="admin-user-card"><div class="admin-user-title"><div><strong>@${esc(u.username||'admin')}</strong><small>${esc(u.display_name||'')} · ผู้ดูแลระบบ</small></div><span class="badge badge-ok">Admin</span></div><div class="admin-user-branches">เข้าถึงทุก HUB/สาขา</div></article>`;const matrixId=`aum-${String(u.user_id).replace(/[^a-zA-Z0-9]/g,'')}`;return`<article class="admin-user-card" data-user-id="${esc(u.user_id)}"><div class="admin-user-title"><div><strong>@${esc(u.username||'')}</strong><small>${esc(u.display_name||'')} · ${esc(u.access_status||'')}</small></div><div class="admin-user-actions"><button class="mini-btn aum-password" type="button">รหัสผ่าน</button><button class="mini-btn aum-toggle" data-action="${u.access_status==='active'?'disable':'enable'}" type="button">${u.access_status==='active'?'ระงับ':'เปิดใช้'}</button></div></div><label class="admin-default-label"><span>HUB เริ่มต้น</span><select class="aum-default"></select></label><div id="${matrixId}" class="access-matrix"></div><button class="btn btn-accent aum-save" type="button">บันทึกสิทธิ์</button></article>`;}).join('')||'<div class="empty-state">ยังไม่มีผู้ใช้</div>';state.users.filter(u=>u.role!=='admin').forEach(u=>{const card=document.querySelector(`.admin-user-card[data-user-id="${CSS.escape(String(u.user_id))}"]`);if(!card)return;const matrix=card.querySelector('.access-matrix'),select=card.querySelector('.aum-default');matrix.innerHTML=state.branches.map(b=>{const a=accessFor(u,b.id),checked=!!a;return`<label class="access-row" data-branch-id="${b.id}"><span class="access-branch"><input class="access-enabled" type="checkbox" ${checked?'checked':''}><b>${esc(b.code)}</b><small>${esc(b.name)}</small></span><span><input class="access-har" type="checkbox" ${a?.can_upload_har?'checked':''} ${checked?'':'disabled'}> HAR</span><span><input class="access-shift" type="checkbox" ${a?.can_manage_shift!==false&&checked?'checked':''} ${checked?'':'disabled'}> ตั้งกะ</span></label>`;}).join('');matrix.querySelectorAll('.access-row').forEach(row=>{const enabled=row.querySelector('.access-enabled'),sync=()=>row.querySelectorAll('.access-har,.access-shift').forEach(c=>c.disabled=!enabled.checked);enabled.addEventListener('change',sync);sync();});fillDefault(select,u);card.querySelector('.aum-save').addEventListener('click',()=>void saveUser(u,card));card.querySelector('.aum-toggle').addEventListener('click',()=>void toggleUser(u,card.querySelector('.aum-toggle').dataset.action));card.querySelector('.aum-password').addEventListener('click',()=>void resetPassword(u));});}
async function saveUser(user,card){const branchAccess=collectAccess(card);if(!branchAccess.length){$('admin-users-status').textContent='ต้องเลือกอย่างน้อย 1 HUB/สาขา';return;}let defaultBranchId=Number(card.querySelector('.aum-default').value);if(!branchAccess.some(a=>a.branchId===defaultBranchId))defaultBranchId=branchAccess[0].branchId;try{$('admin-users-status').textContent=`กำลังบันทึก @${user.username}…`;await api('users',{method:'POST',body:JSON.stringify({action:'update',userId:user.user_id,defaultBranchId,branchAccess})});await loadUsers();$('admin-users-status').textContent=`บันทึกสิทธิ์ @${user.username} แล้ว`;}catch(e){$('admin-users-status').textContent=`บันทึกไม่สำเร็จ: ${e.message}`;}}
async function toggleUser(user,action){try{await api('users',{method:'POST',body:JSON.stringify({action,userId:user.user_id})});await loadUsers();}catch(e){$('admin-users-status').textContent=`เปลี่ยนสถานะไม่สำเร็จ: ${e.message}`;}}
async function resetPassword(user){const password=prompt(`ตั้งรหัสผ่านใหม่สำหรับ @${user.username} (อย่างน้อย 6 ตัว)`);if(!password)return;try{await api('users',{method:'POST',body:JSON.stringify({action:'reset_password',userId:user.user_id,password})});$('admin-users-status').textContent=`เปลี่ยนรหัสผ่าน @${user.username} แล้ว`;}catch(e){$('admin-users-status').textContent=`เปลี่ยนรหัสไม่สำเร็จ: ${e.message}`;}}
async function createUser(event){event.preventDefault();const branchAccess=collectAccess($('acu-access'));if(!branchAccess.length){$('admin-users-status').textContent='เลือกอย่างน้อย 1 HUB/สาขา';return;}let defaultBranchId=Number($('acu-default').value);if(!branchAccess.some(a=>a.branchId===defaultBranchId))defaultBranchId=branchAccess[0].branchId;try{$('admin-users-status').textContent='กำลังสร้างผู้ใช้…';await api('users',{method:'POST',body:JSON.stringify({action:'create',username:$('acu-username').value.trim(),displayName:$('acu-display').value.trim(),password:$('acu-password').value,defaultBranchId,branchAccess})});event.currentTarget.reset();fillDefault($('acu-default'));renderAccessMatrix('acu-access');await loadUsers();$('admin-users-status').textContent='สร้างผู้ใช้แล้ว';}catch(e){$('admin-users-status').textContent=`สร้างผู้ใช้ไม่สำเร็จ: ${e.message}`;}}

function renderBranches(){$('admin-branches-list').innerHTML=state.branches.map(b=>`<article class="admin-branch-card" data-branch-id="${Number(b.id)}"><div class="admin-branch-title"><div><strong>${esc(b.code)} · ${esc(b.name)}</strong><small>${b.has_credential?'HAR พร้อม':'ยังไม่มี HAR'}${b.last_ok_at?` · สำเร็จล่าสุด ${new Date(b.last_ok_at).toLocaleString('th-TH')}`:''}</small></div><span class="badge ${b.is_active?'badge-ok':'badge-neutral'}">${b.is_active?'เปิด':'ปิด'}</span></div><div class="admin-form-fields"><label><span>ชื่อ</span><input class="ab-name" value="${esc(b.name)}"></label><label><span>Own HUB</span><input class="ab-own" value="${esc(b.own_hub_name||'')}" placeholder="กำหนด HUB ของเรา"></label><label class="wide"><span>ชื่อเรียกอื่น</span><input class="ab-alias" value="${esc(Array.isArray(b.hub_aliases)?b.hub_aliases.join(', '):'')}"></label><label class="check-label"><input class="ab-active" type="checkbox" ${b.is_active?'checked':''}><span>เปิดใช้งาน</span></label></div><button class="btn btn-accent ab-save" type="button">บันทึก HUB</button></article>`).join('')||'<div class="empty-state">ยังไม่มี HUB/สาขา</div>';document.querySelectorAll('.admin-branch-card').forEach(card=>card.querySelector('.ab-save').addEventListener('click',()=>void saveBranch(card)));}
async function saveBranch(card){const id=Number(card.dataset.branchId);try{$('admin-branches-status').textContent=`กำลังบันทึก ${branchName(id)}…`;await api('branches',{method:'POST',body:JSON.stringify({action:'update',id,name:card.querySelector('.ab-name').value.trim(),ownHubName:card.querySelector('.ab-own').value.trim(),hubAliases:card.querySelector('.ab-alias').value,isActive:card.querySelector('.ab-active').checked})});await loadBranches();$('admin-branches-status').textContent='บันทึก HUB แล้ว';}catch(e){$('admin-branches-status').textContent=`บันทึกไม่สำเร็จ: ${e.message}`;}}
async function createBranch(event){event.preventDefault();try{$('admin-branches-status').textContent='กำลังเพิ่ม HUB…';await api('branches',{method:'POST',body:JSON.stringify({action:'create',code:$('acb-code').value.trim(),name:$('acb-name').value.trim(),ownHubName:$('acb-own').value.trim(),hubAliases:$('acb-alias').value})});event.currentTarget.reset();await loadBranches();$('admin-branches-status').textContent='เพิ่ม HUB แล้ว · อัปโหลด HAR ของ HUB นี้เมื่อพร้อม';}catch(e){$('admin-branches-status').textContent=`เพิ่ม HUB ไม่สำเร็จ: ${e.message}`;}}
function renderHealth(){const el=$('admin-health-grid');if(!el)return;const now=Date.now();el.innerHTML=state.branches.map(b=>{const ok=Date.parse(String(b.last_ok_at||'')),age=Number.isFinite(ok)?Math.max(0,Math.floor((now-ok)/60000)):null,health=b.last_error?'ควรตรวจ':b.has_credential?'พร้อม':'รอ HAR';return`<article class="admin-health-card"><div><strong>${esc(b.code)}</strong><span>${esc(b.name)}</span></div><b class="${b.last_error?'bad':''}">${health}</b><small>ข้อมูล MS ล่าสุด ${age===null?'ยังไม่มี':age<1?'ไม่ถึง 1 นาที':`${age} นาทีที่แล้ว`}</small><small>Own HUB: ${esc(b.own_hub_name||'ยังไม่ได้ตั้ง')}</small></article>`;}).join('')||'<div class="empty-state">ยังไม่มี HUB</div>';}

async function syncAdmin(branchId=0){try{const out=await api(branchId?`status?branch_id=${branchId}`:'status'),profile=out.data?.profile||{};state.admin=profile.role==='admin'&&profile.access_status==='active';state.branchId=Number(out.data?.branch?.id||branchId||0);state.branches=out.data?.branches||[];$('admin-control-btn')?.classList.toggle('hidden',!state.admin);hideLegacyAdmin();if(state.admin&&$('admin-control-dialog')?.open)await loadAll();}catch{state.admin=false;$('admin-control-btn')?.classList.add('hidden');}}

installUi();
window.addEventListener('ms-branch-ready',event=>{state.branchId=Number(event.detail?.id||0);setTimeout(()=>void syncAdmin(state.branchId),0);});
window.addEventListener('ms-session-reset',()=>{state.admin=false;$('admin-control-btn')?.classList.add('hidden');});
setTimeout(()=>void syncAdmin(),700);
