import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.57.4/+esm';

const CONFIG = {
  supabaseUrl: 'https://afhnfnfbqdqqzrghovfc.supabase.co',
  publishableKey: 'sb_publishable_4GStzbYK3_BhthidusT_hw_DqtzC7qE',
  functionBase: 'https://afhnfnfbqdqqzrghovfc.supabase.co/functions/v1/ms-parcel-api',
};
const supabase = createClient(CONFIG.supabaseUrl, CONFIG.publishableKey, { auth: { persistSession: true, autoRefreshToken: true, detectSessionInUrl: true } });
const $ = (id) => document.getElementById(id);
const fmt = new Intl.NumberFormat('th-TH');
const esc = (v) => String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const val = (v, dash='-') => v === null || v === undefined || v === '' ? dash : String(v);
const kg = (v) => { const n=Number(v); return Number.isFinite(n) ? `${(n/1000).toLocaleString('th-TH',{maximumFractionDigits:3})} kg` : val(v); };
const customerType = (r) => r.ka_name || r.ka_id ? 'KA' : val(r.customer_type_category);
const state = {
  session:null, profileRole:'viewer', accessStatus:'pending', canUploadHar:false, profileBranchId:0,
  branches:[], branchId:0, page:1, pageSize:100, rows:[], total:0, hash:'', timer:null, summaryTimer:null,
  loading:false, summaryLoading:false, users:[], adminBranches:[]
};
const branchId = () => Number(state.branchId || 0);
const liveKey = () => `b:${branchId()}:p:${state.page}:s:${state.pageSize}`;
const summaryKey = () => `b:${branchId()}:summary:transfer-summary`;

setInterval(() => $('live-clock').textContent = new Date().toLocaleString('th-TH',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}),1000);

async function publicApi(route, options={}) {
  const headers=new Headers(options.headers||{}); headers.set('apikey',CONFIG.publishableKey);
  const res=await fetch(`${CONFIG.functionBase}/${route}`,{...options,headers});
  const data=await res.json().catch(()=>({ok:false,message:`HTTP ${res.status}`}));
  if(!res.ok||data.ok===false) throw new Error(data.message||`HTTP ${res.status}`); return data;
}
async function api(route, options={}) {
  if(!state.session?.access_token) throw new Error('กรุณาเข้าสู่ระบบ');
  const headers=new Headers(options.headers||{}); headers.set('Authorization',`Bearer ${state.session.access_token}`); headers.set('apikey',CONFIG.publishableKey);
  const res=await fetch(`${CONFIG.functionBase}/${route}`,{...options,headers});
  const data=await res.json().catch(()=>({ok:false,message:`HTTP ${res.status}`}));
  if(!res.ok||data.ok===false) throw new Error(data.message||`HTTP ${res.status}`); return data;
}
function branchQuery(route){const sep=route.includes('?')?'&':'?';return `${route}${sep}branch_id=${branchId()}`;}
function setConnection(type,text){$('connection-badge').className=`badge ${type==='ok'?'badge-ok':type==='bad'?'badge-bad':'badge-neutral'}`;$('connection-badge').textContent=text;$('live-dot').className=`live-dot ${type==='ok'?'live':type==='bad'?'error':'stale'}`;}
function scheduleLive(ms){clearTimeout(state.timer);state.timer=setTimeout(()=>loadPage(false),document.hidden?60000:Math.max(500,ms));}
function scheduleSummary(ms){clearTimeout(state.summaryTimer);state.summaryTimer=setTimeout(()=>loadSummary(false),document.hidden?60000:Math.max(1000,ms));}
function remainingMs(expiresAt,fallback=1000){const n=Date.parse(String(expiresAt||''));return Number.isFinite(n)?Math.max(0,n-Date.now()+120):fallback;}
function currentBranch(){return state.branches.find(b=>Number(b.id)===branchId())||null;}
function branchLabel(id){const b=(state.adminBranches.length?state.adminBranches:state.branches).find(x=>Number(x.id)===Number(id));return b?`${b.code} · ${b.name}`:`สาขา #${id}`;}
function canUploadCurrentBranch(){return state.profileRole==='admin'||(state.canUploadHar&&Number(state.profileBranchId)===branchId());}

async function claimRefresh(cacheKey){const{data,error}=await supabase.rpc('claim_cache_refresh',{p_branch_id:branchId(),p_cache_key:cacheKey,p_lease_seconds:6});if(error)throw error;return data===true;}
async function readLiveMeta(){const{data,error}=await supabase.from('live_cache_pages').select('cache_key,branch_id,source_total,source_updated_at,expires_at,content_hash,previous_hash').eq('cache_key',liveKey()).eq('branch_id',branchId()).maybeSingle();if(error)throw error;return data;}
async function readLiveDelta(){const{data,error}=await supabase.from('live_cache_pages').select('delta_payload,source_total,source_updated_at,expires_at,content_hash,previous_hash').eq('cache_key',liveKey()).eq('branch_id',branchId()).maybeSingle();if(error)throw error;return data;}
async function readLiveFull(){const{data,error}=await supabase.from('live_cache_pages').select('payload,source_total,source_updated_at,expires_at,content_hash,previous_hash').eq('cache_key',liveKey()).eq('branch_id',branchId()).maybeSingle();if(error)throw error;return data;}
async function readSummaryCache(){const{data,error}=await supabase.from('summary_cache').select('payload,source_updated_at,expires_at,content_hash').eq('cache_key',summaryKey()).eq('branch_id',branchId()).maybeSingle();if(error)throw error;return data;}

function applyDelta(delta){if(!delta||!Array.isArray(delta.order))return false;const map=new Map(state.rows.map(r=>[String(r?.pno||''),r]));for(const pno of(delta.removed||[]))map.delete(String(pno));for(const row of(delta.upserts||[])){const pno=String(row?.pno||'');if(pno)map.set(pno,row);}const next=delta.order.map(p=>map.get(String(p))).filter(Boolean);if(!next.length&&delta.order.length)return false;state.rows=next;return true;}
function updateLiveDisplay(sourceAt,note='live'){renderFilters();renderRows();$('last-refresh').textContent=`ตรวจ MS ล่าสุด ${new Date(sourceAt||Date.now()).toLocaleString('th-TH')} · ${note}`;$('source-sync').textContent=`${fmt.format(state.total)} รายการ · ${currentBranch()?.code||''}`;setConnection('ok','ออนไลน์');}
async function applySharedChange(meta){
  if(!meta?.content_hash||meta.content_hash===state.hash)return false;
  if(state.hash&&String(meta.previous_hash||'')===state.hash){const d=await readLiveDelta();if(d&&String(d.previous_hash||'')===state.hash&&String(d.content_hash||'')===String(meta.content_hash||'')&&applyDelta(d.delta_payload)){state.total=Number(d.source_total||0);state.hash=String(d.content_hash||'');updateLiveDisplay(d.source_updated_at,'delta cache');return true;}}
  const full=await readLiveFull();const rows=full?.payload?.rows;if(!Array.isArray(rows))return false;state.rows=rows;state.total=Number(full.source_total??full.payload?.total??0);state.hash=String(full.content_hash||'');updateLiveDisplay(full.source_updated_at,'shared cache');return true;
}
function applyEdgeLive(out){const d=out?.data||{};let note=out?.meta?.cache||'edge';if(d.notModified){state.total=Number(d.total??state.total);state.hash=String(d.hash||state.hash);note='ไม่เปลี่ยน';}else if(d.delta&&applyDelta(d.delta)){state.total=Number(d.total??state.total);state.hash=String(d.hash||state.hash);note='delta';}else if(Array.isArray(d.rows)){state.rows=d.rows;state.total=Number(d.total||0);state.hash=String(d.hash||'');note='full';}updateLiveDisplay(d.sourceAt,out?.meta?.stale?'ใช้ cache ล่าสุด':note);if(out?.meta?.stale)setConnection('bad','ใช้ cache ล่าสุด');return Number(out?.meta?.ttlMs||0);}
function renderSummary(d){d=d||{};$('m-total').textContent=fmt.format(d.total||0);$('m-day1').textContent=fmt.format(d.day1||0);$('m-day2').textContent=fmt.format(d.day2||0);$('m-day3').textContent=fmt.format(d.day3||0);$('m-day4').textContent=fmt.format(d.day4||0);$('m-day5').textContent=fmt.format(d.day5plus||0);$('m-store').textContent=d.storeName||d.storeId||currentBranch()?.name||'-';}

function renderBranchSelect(){const el=$('branch-select');el.innerHTML=state.branches.map(b=>`<option value="${Number(b.id)}">${esc(b.code)} · ${esc(b.name)}</option>`).join('');if(branchId())el.value=String(branchId());$('branch-select-wrap').classList.toggle('hidden',!state.session||state.branches.length===0);}
function updateHeaderPermissions(){const active=state.accessStatus==='active';$('manage-users-btn').classList.toggle('hidden',!(active&&state.profileRole==='admin'));$('manage-branches-btn').classList.toggle('hidden',!(active&&state.profileRole==='admin'));$('upload-har-btn').classList.toggle('hidden',!(active&&branchId()&&canUploadCurrentBranch()));$('refresh-btn').classList.toggle('hidden',!active);$('logout-btn').classList.toggle('hidden',!state.session);}
async function refreshStatus(preferred=0){const route=preferred?`status?branch_id=${preferred}`:'status';const out=await api(route);const d=out.data||{},p=d.profile||{};state.profileRole=p.role||'viewer';state.accessStatus=p.access_status||'pending';state.canUploadHar=!!p.can_upload_har;state.profileBranchId=Number(p.branch_id||0);state.branches=Array.isArray(d.branches)?d.branches:[];let chosen=preferred||Number(localStorage.getItem('ms-parcel-branch-id')||0)||state.profileBranchId||Number(d.branch?.id||0)||Number(state.branches[0]?.id||0);if(!state.branches.some(b=>Number(b.id)===chosen))chosen=Number(state.branches[0]?.id||0);state.branchId=chosen;if(chosen)localStorage.setItem('ms-parcel-branch-id',String(chosen));renderBranchSelect();updateHeaderPermissions();const conn=d.connection;if(conn?.last_error)setConnection('bad','MS มีปัญหา');else if(conn?.credential_updated_at)setConnection('ok','ออนไลน์');else setConnection('neutral','ยังไม่มี HAR');$('source-sync').textContent=currentBranch()?.name||d.branch?.name||'ยังไม่ได้เลือกสาขา';return d;}

async function boot(){const{data}=await supabase.auth.getSession();await setSession(data.session);supabase.auth.onAuthStateChange(async(event,session)=>{const sameUser=state.session?.user?.id&&session?.user?.id===state.session.user.id;if(sameUser&&(event==='TOKEN_REFRESHED'||event==='SIGNED_IN')){state.session=session;return;}await setSession(session);});}
async function setSession(session){state.session=session;clearTimeout(state.timer);clearTimeout(state.summaryTimer);state.hash='';state.rows=[];state.total=0;if(!session){$('login-dialog').showModal();$('branch-select-wrap').classList.add('hidden');updateHeaderPermissions();$('empty-state').textContent='กรุณาเข้าสู่ระบบ';$('empty-state').classList.remove('hidden');$('table-wrap').classList.add('hidden');$('mobile-cards').classList.add('hidden');setConnection('neutral','ยังไม่ได้เข้าสู่ระบบ');$('source-sync').textContent='ยังไม่ได้เชื่อมต่อ';return;}if($('login-dialog').open)$('login-dialog').close();try{await refreshStatus();if(state.accessStatus!=='active'){setConnection('neutral',state.accessStatus==='disabled'?'ถูกระงับ':'ยังไม่เปิดใช้งาน');$('empty-state').textContent='บัญชีนี้ยังไม่เปิดใช้งาน';$('empty-state').classList.remove('hidden');return;}if(!branchId()){setConnection('neutral','ยังไม่มีสาขา');$('empty-state').textContent='ยังไม่ได้ตั้งค่าสาขา';$('empty-state').classList.remove('hidden');return;}await Promise.allSettled([loadSummary(false),loadPage(false)]);}catch(e){setConnection('bad','เชื่อมต่อไม่ได้');$('source-sync').textContent=e.message;}}

async function loadSummary(force=false){if(!state.session||state.accessStatus!=='active'||!branchId()||state.summaryLoading)return;state.summaryLoading=true;try{let c=await readSummaryCache();if(c?.payload)renderSummary(c.payload);const fresh=c&&Date.parse(String(c.expires_at||''))>Date.now();if(fresh&&!force){scheduleSummary(remainingMs(c.expires_at,60000));return;}const leader=await claimRefresh(summaryKey());if(!leader){scheduleSummary(900);return;}const out=await api(branchQuery('summary'));renderSummary(out.data);if(out.meta?.stale)setConnection('bad','ใช้ cache ล่าสุด');scheduleSummary(Number(out.meta?.ttlMs||60000));}catch(e){scheduleSummary(15000);}finally{state.summaryLoading=false;}}
async function loadPage(force=false){if(!state.session||state.accessStatus!=='active'||!branchId()||state.loading)return;state.loading=true;try{let meta=await readLiveMeta();if(meta?.content_hash!==state.hash)await applySharedChange(meta);const fresh=meta&&Date.parse(String(meta.expires_at||''))>Date.now();if(fresh&&!force){scheduleLive(remainingMs(meta.expires_at,8000));return;}const leader=await claimRefresh(liveKey());if(!leader){scheduleLive(900);return;}const known=state.hash?`&known_hash=${encodeURIComponent(state.hash)}`:'';const out=await api(`live?page=${state.page}&page_size=${state.pageSize}&branch_id=${branchId()}${known}`);const ttl=applyEdgeLive(out)||8000;scheduleLive(ttl+100);}catch(e){if(!state.rows.length){$('empty-state').textContent='ยังไม่มีข้อมูลในหน้าปัจจุบัน';$('empty-state').classList.remove('hidden');}else{$('last-refresh').textContent=`รีเฟรชไม่สำเร็จ · ใช้ข้อมูลล่าสุด · ${e.message}`;}setConnection('bad','รีเฟรชไม่สำเร็จ');scheduleLive(document.hidden?60000:15000);}finally{state.loading=false;}}

function unique(field){return[...new Set(state.rows.map(r=>val(r[field],'')).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'th'));}
function fillSelect(id,values){const el=$(id),keep=el.value;el.innerHTML='<option value="">ทั้งหมด</option>'+values.map(v=>`<option>${esc(v)}</option>`).join('');if(values.includes(keep))el.value=keep;}
function renderFilters(){fillSelect('status-filter',unique('state_name'));fillSelect('hub-filter',unique('dst_hub_name'));fillSelect('branch-filter',unique('dst_store_name'));}
function filteredRows(){const q=$('search-input').value.trim().toLowerCase(),st=$('status-filter').value,hub=$('hub-filter').value,br=$('branch-filter').value;return state.rows.filter(r=>{if(st&&val(r.state_name)!==st)return false;if(hub&&val(r.dst_hub_name)!==hub)return false;if(br&&val(r.dst_store_name)!==br)return false;if(!q)return true;return Object.values(r).some(v=>String(v??'').toLowerCase().includes(q));});}
function stack(a,b){return`<div class="cell-stack"><span>${esc(val(a))}</span>${b?`<small>${esc(val(b,''))}</small>`:''}</div>`;}
function renderRows(){const rows=filteredRows();$('empty-state').classList.toggle('hidden',rows.length>0);$('table-wrap').classList.toggle('hidden',rows.length===0);$('mobile-cards').classList.toggle('hidden',rows.length===0);if(!rows.length)$('empty-state').textContent='ไม่พบข้อมูลในหน้าปัจจุบัน';$('table-body').innerHTML=rows.map(r=>`<tr><td>${esc(val(r.pno))}</td><td><span class="status-chip">${esc(val(r.state_name))}</span></td><td>${stack(`${Number(r.cod_amount||0).toLocaleString('th-TH',{minimumFractionDigits:2})} บาท`,kg(r.store_weight))}</td><td>${stack(r.plan_leave_time,r.real_arrive_time)}</td><td>${esc(val(r.pack_num))}</td><td>${esc(val(r.marker_category_name))}</td><td>${stack(r.LastAction_name,r.LastActionTime)}</td><td>${stack(r.staff_info_name,r.staff_info_phone)}</td><td>${stack(r.dst_hub_name,r.dst_store_name)}</td><td>${stack(`${val(r.dst_province_name,'')} ${val(r.dst_city_name,'')}`.trim(),r.dst_postal_code)}</td><td>${stack(customerType(r),r.ka_name)}</td></tr>`).join('');$('mobile-cards').innerHTML=rows.map(r=>`<article class="mobile-card"><h3>${esc(val(r.pno))} · ${esc(val(r.state_name))}</h3><dl><dt>COD / น้ำหนัก</dt><dd>${esc(Number(r.cod_amount||0).toLocaleString('th-TH',{minimumFractionDigits:2}))} / ${esc(kg(r.store_weight))}</dd><dt>แผน / ถึงจริง</dt><dd>${esc(val(r.plan_leave_time))}<br>${esc(val(r.real_arrive_time))}</dd><dt>แบ็กกิ้ง</dt><dd>${esc(val(r.pack_num))}</dd><dt>ล่าสุด</dt><dd>${esc(val(r.LastAction_name))}<br>${esc(val(r.LastActionTime))}</dd><dt>ปลายทาง</dt><dd>${esc(val(r.dst_hub_name))}<br>${esc(val(r.dst_store_name))}</dd><dt>ลูกค้า</dt><dd>${esc(val(r.ka_name))}</dd></dl></article>`).join('');const pages=Math.max(1,Math.ceil(state.total/state.pageSize));$('page-info').textContent=`หน้า ${state.page} / ${fmt.format(pages)} · แสดง ${fmt.format(rows.length)} จาก ${fmt.format(state.total)}`;$('prev-btn').disabled=state.page<=1;$('next-btn').disabled=state.page>=pages;}

function branchOptions(selected){return(state.adminBranches.length?state.adminBranches:state.branches).map(b=>`<option value="${Number(b.id)}" ${Number(b.id)===Number(selected)?'selected':''}>${esc(b.code)} · ${esc(b.name)}</option>`).join('');}
async function loadUsers(){$('users-status').textContent='กำลังอ่านรายชื่อ…';try{const out=await api('users');state.users=out.data?.users||[];state.adminBranches=out.data?.branches||[];$('new-user-branch').innerHTML=branchOptions(state.branchId);$('users-status').textContent=`ทั้งหมด ${state.users.length} บัญชี`;const branchMap=new Map(state.adminBranches.map(b=>[Number(b.id),b]));$('users-list').innerHTML=state.users.map(u=>{const b=branchMap.get(Number(u.branch_id));if(u.role==='admin')return`<article class="user-row"><div><strong>@${esc(u.username||'admin')}</strong><small>${esc(u.display_name||'Owner')} · Admin · ${esc(b?.code||'-')}</small></div><span class="badge badge-ok">Admin</span></article>`;return`<article class="user-row user-row-edit" data-user-id="${esc(u.user_id)}"><div><strong>@${esc(u.username)}</strong><small>${esc(u.display_name||'')} · ${esc(u.access_status)} · HAR ${u.can_upload_har?'ได้':'ไม่ได้'}</small></div><div class="user-edit-controls"><select class="user-branch-select">${branchOptions(u.branch_id)}</select><label class="mini-check"><input class="user-har-check" type="checkbox" ${u.can_upload_har?'checked':''}/>HAR</label><button class="btn btn-header user-save" type="button">บันทึกสิทธิ์</button><button class="btn btn-header user-password" type="button">เปลี่ยนรหัส</button><button class="btn ${u.access_status==='active'?'btn-danger':'btn-accent'} user-toggle" type="button" data-action="${u.access_status==='active'?'disable':'enable'}">${u.access_status==='active'?'ระงับ':'เปิดใช้'}</button></div></article>`;}).join('')||'<div class="empty-state">ยังไม่มีผู้ใช้</div>';bindUserActions();}catch(e){$('users-status').textContent=`โหลดไม่สำเร็จ: ${e.message}`;}}
function bindUserActions(){document.querySelectorAll('.user-row-edit').forEach(row=>{const id=row.dataset.userId;row.querySelector('.user-save')?.addEventListener('click',async()=>{try{await api('users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'update',userId:id,branchId:Number(row.querySelector('.user-branch-select').value),canUploadHar:row.querySelector('.user-har-check').checked})});await loadUsers();}catch(e){$('users-status').textContent=`ไม่สำเร็จ: ${e.message}`;}});row.querySelector('.user-password')?.addEventListener('click',async()=>{const password=prompt('ตั้งรหัสผ่านใหม่อย่างน้อย 8 ตัวอักษร');if(!password)return;try{await api('users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'reset_password',userId:id,password})});$('users-status').textContent='เปลี่ยนรหัสผ่านแล้ว';}catch(e){$('users-status').textContent=`ไม่สำเร็จ: ${e.message}`;}});row.querySelector('.user-toggle')?.addEventListener('click',async e=>{try{await api('users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:e.currentTarget.dataset.action,userId:id})});await loadUsers();}catch(err){$('users-status').textContent=`ไม่สำเร็จ: ${err.message}`;}});});}

async function loadBranches(){$('branches-status').textContent='กำลังอ่านสาขา…';try{const out=await api('branches');state.adminBranches=out.data?.branches||[];$('branches-status').textContent=`ทั้งหมด ${state.adminBranches.length} สาขา`;$('branches-list').innerHTML=state.adminBranches.map(b=>`<article class="user-row"><div><strong>${esc(b.code)} · ${esc(b.name)}</strong><small>${b.store_id?`Store ${esc(b.store_id)}`:'ยังไม่มี Store ID'} · HAR ${b.has_credential?'พร้อม':'ยังไม่มี'}${b.last_error?` · Error: ${esc(b.last_error)}`:''}</small></div><span class="badge ${b.has_credential?'badge-ok':'badge-neutral'}">${b.has_credential?'เชื่อมแล้ว':'รอ HAR'}</span></article>`).join('');}catch(e){$('branches-status').textContent=`โหลดไม่สำเร็จ: ${e.message}`;}}
async function refreshBranchListAndStatus(preferred=state.branchId){await refreshStatus(preferred);await Promise.allSettled([loadSummary(true),loadPage(true)]);}

$('login-form').addEventListener('submit',async e=>{e.preventDefault();$('login-error').classList.add('hidden');try{const out=await publicApi('login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('username').value.trim(),password:$('password').value})});const{error}=await supabase.auth.setSession(out.data.session);if(error)throw error;}catch(err){$('login-error').textContent=err.message;$('login-error').classList.remove('hidden');}});
$('logout-btn').addEventListener('click',()=>supabase.auth.signOut());
$('refresh-btn').addEventListener('click',()=>Promise.allSettled([loadSummary(true),loadPage(true)]));
$('branch-select').addEventListener('change',async()=>{const id=Number($('branch-select').value);if(!id||id===state.branchId)return;state.branchId=id;localStorage.setItem('ms-parcel-branch-id',String(id));state.page=1;state.hash='';state.rows=[];state.total=0;clearTimeout(state.timer);clearTimeout(state.summaryTimer);renderRows();try{await refreshStatus(id);await Promise.allSettled([loadSummary(false),loadPage(false)]);}catch(e){setConnection('bad','สลับสาขาไม่สำเร็จ');}});

$('manage-users-btn').addEventListener('click',()=>{$('users-dialog').showModal();loadUsers();});$('users-close').addEventListener('click',()=>$('users-dialog').close());$('users-refresh').addEventListener('click',loadUsers);
$('create-user-form').addEventListener('submit',async e=>{e.preventDefault();$('users-status').textContent='กำลังสร้างผู้ใช้…';try{await api('users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'create',username:$('new-username').value.trim(),displayName:$('new-display-name').value.trim(),password:$('new-password').value,branchId:Number($('new-user-branch').value),canUploadHar:$('new-can-upload-har').checked})});e.currentTarget.reset();$('new-user-branch').innerHTML=branchOptions(state.branchId);$('users-status').textContent='สร้างผู้ใช้สำเร็จ';await loadUsers();}catch(err){$('users-status').textContent=`สร้างไม่สำเร็จ: ${err.message}`;}});

$('manage-branches-btn').addEventListener('click',()=>{$('branches-dialog').showModal();loadBranches();});$('branches-close').addEventListener('click',()=>$('branches-dialog').close());$('branches-refresh').addEventListener('click',loadBranches);
$('create-branch-form').addEventListener('submit',async e=>{e.preventDefault();$('branches-status').textContent='กำลังเพิ่มสาขา…';try{const out=await api('branches',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'create',code:$('new-branch-code').value.trim(),name:$('new-branch-name').value.trim()})});e.currentTarget.reset();$('branches-status').textContent='เพิ่มสาขาแล้ว · เลือกสาขานั้นแล้วอัปโหลด HAR';await loadBranches();await refreshStatus(Number(out.data?.branch?.id||state.branchId));}catch(err){$('branches-status').textContent=`เพิ่มไม่สำเร็จ: ${err.message}`;}});

$('upload-har-btn').addEventListener('click',()=>{const b=currentBranch();$('har-branch-note').textContent=`HAR นี้จะอัปเดตเฉพาะ ${b?.code||''} · ${b?.name||''}`;$('har-status').textContent='';$('har-dialog').showModal();});$('har-close').addEventListener('click',()=>$('har-dialog').close());
$('har-form').addEventListener('submit',async e=>{e.preventDefault();const file=$('har-file').files?.[0];if(!file)return;$('har-status').textContent='กำลังตรวจ HAR…';try{const text=await file.text();const out=await api(branchQuery('har'),{method:'POST',headers:{'Content-Type':'application/json'},body:text});$('har-status').textContent=`สำเร็จ · Store ${out.data.storeId}`;state.hash='';state.rows=[];state.total=0;await refreshBranchListAndStatus(branchId());}catch(err){$('har-status').textContent=`ไม่สำเร็จ: ${err.message}`;}});

['search-input','status-filter','hub-filter','branch-filter'].forEach(id=>$(id).addEventListener(id==='search-input'?'input':'change',renderRows));
$('page-size').addEventListener('change',()=>{state.pageSize=Number($('page-size').value);state.page=1;state.hash='';state.rows=[];state.total=0;loadPage(false);});
$('prev-btn').addEventListener('click',()=>{if(state.page>1){state.page--;state.hash='';state.rows=[];loadPage(false);}});
$('next-btn').addEventListener('click',()=>{state.page++;state.hash='';state.rows=[];loadPage(false);});
document.addEventListener('visibilitychange',()=>{clearTimeout(state.timer);clearTimeout(state.summaryTimer);if(state.session&&state.accessStatus==='active'&&branchId()){if(document.hidden){scheduleLive(60000);scheduleSummary(60000);}else{scheduleLive(300);scheduleSummary(500);}}});

boot();