const $=(id)=>document.getElementById(id);
const esc=(v)=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const num=(v)=>Number(v||0).toLocaleString('th-TH');
let analytics=null;

function labelRoute(route){return route==='fd'?'FD':route==='lh'?'LH':'อื่น';}
function groupDestinations(data){const map=new Map();for(const bag of(Array.isArray(data?.bagGroups)?data.bagGroups:[])){if(!['fd','lh'].includes(bag.route)||!bag.destination)continue;const key=`${bag.route}\u001f${bag.destination}`,g=map.get(key)||{route:bag.route,name:bag.destination,packCount:0,parcelCount:0,over24:0,over48:0,residual:0,stuck:0,bags:[]};g.packCount++;g.parcelCount+=Number(bag.currentCount||0);g.over24+=Number(bag.over24||0);g.over48+=Number(bag.over48||0);if(Number(bag.currentCount||0)<=10&&Number(bag.peakObserved||bag.currentCount||0)>Number(bag.currentCount||0))g.residual++;if(Number(bag.currentCount||0)<=10&&Number(bag.stagnantMinutes||0)>=60)g.stuck++;g.bags.push(bag);map.set(key,g);}return[...map.values()].sort((a,b)=>b.over48-a.over48||b.stuck-a.stuck||b.parcelCount-a.parcelCount||a.name.localeCompare(b.name,'th'));}
function bagStatus(b){const current=Number(b.currentCount||0),peak=Number(b.peakObserved||current),delta=b.deltaCount===null||b.deltaCount===undefined?null:Number(b.deltaCount),stagnant=Number(b.stagnantMinutes||0);if(stagnant>=60&&current<=10)return`คงที่ ${num(stagnant)} นาที`;if(delta!==null&&delta<0)return`ลด ${num(Math.abs(delta))} ชิ้นจากรอบก่อน`;if(delta!==null&&delta>0)return`เพิ่ม ${num(delta)} ชิ้นจากรอบก่อน`;if(peak>current)return`พบ ${num(current)} / เคยพบสูงสุด ${num(peak)}`;return'กำลังติดตาม';}
function render(){const host=$('bag-destination-control');if(!host||!analytics)return;const complete=analytics.complete===true,groups=groupDestinations(analytics);host.innerHTML=`<div class="bag-destination-head"><div><h3>ตรวจเลขแบ็กกิ้งตามปลายทาง</h3><span>HUB / สาขาปลายทาง → เลขแบ็กกิ้ง → จำนวนพัสดุที่ยังพบ</span></div><div class="data-truth-badge ${complete?'ok':'warn'}">${complete?'ข้อมูล Snapshot ครบ':'ข้อมูลยังไม่ครบ · ไม่ใช้เทียบแนวโน้ม'}</div></div><div class="bag-destination-summary"><span><b>${num(groups.reduce((s,g)=>s+g.packCount,0))}</b> เลขแบ็กกิ้งที่พบ</span><span><b>${num(groups.reduce((s,g)=>s+g.parcelCount,0))}</b> ชิ้นภายใต้เลขแบ็กกิ้ง</span><span><b>${num(groups.reduce((s,g)=>s+g.residual,0))}</b> เลขที่เหลือท้าย</span><span><b>${num(groups.reduce((s,g)=>s+g.stuck,0))}</b> เลขที่คงที่ ≥60 นาที</span></div><div class="bag-destination-list">${groups.map((g,i)=>`<details class="bag-destination-group ${g.over48?'critical':''}" ${i<3?'open':''}><summary><div><span class="route-tag ${g.route}">${labelRoute(g.route)}</span><strong>${esc(g.name)}</strong></div><div class="bag-destination-kpis"><b>${num(g.packCount)} เลข</b><span>${num(g.parcelCount)} ชิ้น</span>${g.residual?`<span>${num(g.residual)} เหลือท้าย</span>`:''}${g.over48?`<span class="danger">${num(g.over48)} >48ชม.</span>`:''}</div></summary><div class="bag-residual-grid">${g.bags.sort((a,b)=>Number(b.over48||0)-Number(a.over48||0)||Number(b.stagnantMinutes||0)-Number(a.stagnantMinutes||0)||Number(a.currentCount||0)-Number(b.currentCount||0)).slice(0,80).map(b=>{const current=Number(b.currentCount||0),peak=Number(b.peakObserved||current);return`<button class="bag-residual-row" type="button" data-pack-focus="${esc(b.pack)}"><span><strong>${esc(b.pack)}</strong><small>${bagStatus(b)}</small></span><span><b>${num(current)}</b><small>ชิ้นปัจจุบัน</small></span><span><b>${peak>current?num(peak):'—'}</b><small>${peak>current?'เคยพบสูงสุด':'ยังไม่มีรอบเทียบ'}</small></span><span><b>${Number(b.maxAgeHours||0).toFixed(1)}</b><small>อายุสูงสุด (ชม.)</small></span></button>`;}).join('')}</div>${g.bags.length>80?`<div class="bag-more-note">แสดง 80 จาก ${num(g.bags.length)} เลข · ใช้ช่องค้นหาเลขแบ็กกิ้งเพื่อเจาะรายการ</div>`:''}</details>`).join('')||'<div class="empty-state">ยังไม่พบเลขแบ็กกิ้งในข้อมูลชุดนี้</div>'}</div>`;host.querySelectorAll('[data-pack-focus]').forEach(btn=>btn.addEventListener('click',()=>focusPack(btn.dataset.packFocus)));}
function focusPack(pack){const input=$('bag-search');if(input){input.value=pack;input.dispatchEvent(new Event('input',{bubbles:true}));input.scrollIntoView({behavior:'smooth',block:'center'});input.focus();}navigator.clipboard?.writeText(pack).catch(()=>{});}
function install(){if($('bag-destination-control'))return;const page=document.querySelector('[data-page-view="bagging"]');if(!page)return;const panel=page.querySelector('.bag-panel');const section=document.createElement('section');section.id='bag-destination-control';section.className='panel bag-destination-control';page.insertBefore(section,panel||page.firstChild);}
function languageFix(root=document){const replacements=[['ตรวจการสร้างแบ็ก','ตรวจพัสดุที่ไม่พบเลขแบ็กกิ้ง'],['ไม่มีแบ็ก ≥24ชม.','ไม่พบเลขแบ็กกิ้ง ≥24ชม.'],['พัสดุมีแบ็ก','พบเลขแบ็กกิ้ง'],['เลขแบ็ก','เลขแบ็กกิ้งที่พบ']];const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const node of nodes){let text=node.nodeValue||'',next=text;for(const[from,to]of replacements)next=next.replaceAll(from,to);if(next!==text)node.nodeValue=next;}}
install();languageFix();
new MutationObserver(mutations=>{for(const m of mutations){for(const n of m.addedNodes)if(n.nodeType===Node.ELEMENT_NODE)languageFix(n);}}).observe(document.body,{childList:true,subtree:true});
window.addEventListener('ms-full-analytics',event=>{analytics=event.detail||null;render();});
window.addEventListener('ms-branch-ready',()=>{analytics=null;const host=$('bag-destination-control');if(host)host.innerHTML='<div class="work-empty"><strong>กำลังอ่านข้อมูลเลขแบ็กกิ้ง</strong><span>ใช้ Snapshot กลางของ HUB เดียวกับหน้าอื่น</span></div>';});
if(window.__MS_FULL_ANALYTICS){analytics=window.__MS_FULL_ANALYTICS;render();}
