import { supabase } from './auth-client.js?v=20260906-control-room-v32';

const FUNCTION_BASE='https://afhnfnfbqdqqzrghovfc.supabase.co/functions/v1/ms-parcel-api';
const PUBLISHABLE_KEY='sb_publishable_4GStzbYK3_BhthidusT_hw_DqtzC7qE';
const $=(id)=>document.getElementById(id);
const esc=(v)=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const state={branchId:0,branch:null,shifts:[],canManage:false,editingId:0,backendCurrentShift:null};

function bangkokDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
function timeToMinute(value){const m=/^(\d{2}):(\d{2})$/.exec(String(value||''));return m?Number(m[1])*60+Number(m[2]):0;}
function minuteToTime(value){const n=Math.max(0,Math.min(1439,Number(value)||0));return`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;}
function currentMinute(){const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Bangkok',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date()),get=t=>parts.find(p=>p.type===t)?.value||'0';return Number(get('hour'))*60+Number(get('minute'));}
function isCurrentShift(s){if(!s?.is_active)return false;const now=currentMinute(),start=Number(s.start_minute),end=Number(s.end_minute);return start<end?(now>=start&&now<end):(now>=start||now<end);}
async function api(route,options={}){const{data}=await supabase.auth.getSession();const token=data?.session?.access_token;if(!token)throw new Error('กรุณาเข้าสู่ระบบ');const headers=new Headers(options.headers||{});headers.set('Authorization',`Bearer ${token}`);headers.set('apikey',PUBLISHABLE_KEY);if(options.body&&!headers.has('Content-Type'))headers.set('Content-Type','application/json');const res=await fetch(`${FUNCTION_BASE}/${route}`,{...options,headers});const out=await res.json().catch(()=>({ok:false,message:`HTTP ${res.status}`}));if(!res.ok||out.ok===false)throw new Error(out.message||`HTTP ${res.status}`);return out;}

function installUi(){
  if($('shift-settings-btn'))return;
  const actions=document.querySelector('.topbar-actions');
  if(actions){const pill=document.createElement('span');pill.id='current-shift-pill';pill.className='shift-pill hidden';pill.textContent='ยังไม่ได้ตั้งกะ';actions.prepend(pill);const btn=document.createElement('button');btn.id='shift-settings-btn';btn.className='btn btn-header hidden';btn.type='button';btn.textContent='ตั้งค่ากะ';btn.addEventListener('click',()=>{resetForm();$('shift-dialog').showModal();void loadShifts();});const har=$('upload-har-btn');actions.insertBefore(btn,har||null);}
  const dialog=document.createElement('dialog');dialog.id='shift-dialog';dialog.innerHTML=`<div class="dialog-card shift-dialog-card"><button id="shift-close" class="dialog-close" type="button">×</button><div class="shift-dialog-head"><div><h2>ตั้งค่ากะ</h2><p id="shift-branch-note">-</p></div><span id="shift-manage-badge" class="badge badge-neutral">อ่านอย่างเดียว</span></div><form id="shift-form" class="shift-form-grid"><input id="shift-edit-id" type="hidden"><label><span>ชื่อกะ</span><input id="shift-name" maxlength="50" placeholder="เช่น กะเช้า" required></label><label><span>เริ่ม</span><input id="shift-start" type="time" required></label><label><span>สิ้นสุด</span><input id="shift-end" type="time" required></label><label><span>มีผลตั้งแต่</span><input id="shift-effective" type="date" required></label><label><span>ลำดับ</span><input id="shift-order" type="number" min="0" max="999" value="0"></label><label class="check-label"><input id="shift-active" type="checkbox" checked><span>เปิดใช้งาน</span></label><div class="shift-form-actions"><button id="shift-cancel-edit" class="btn btn-header hidden" type="button">ยกเลิกแก้ไข</button><button id="shift-save" class="btn btn-accent" type="submit">เพิ่มกะ</button></div></form><div id="shift-status" class="sync-text"></div><div id="shift-list" class="shift-list"></div><div class="shift-help"><strong>กะข้ามวันรองรับอัตโนมัติ</strong><span>เช่น 20:00–04:00 จะถือเป็นกะเดียวกันข้ามเที่ยงคืน การเปลี่ยนเวลาใช้ Effective Date เพื่อไม่เปลี่ยนความหมายของข้อมูลย้อนหลัง</span></div></div>`;document.body.appendChild(dialog);
  $('shift-close').addEventListener('click',()=>dialog.close());$('shift-cancel-edit').addEventListener('click',resetForm);$('shift-form').addEventListener('submit',saveShift);
}
function resetForm(){state.editingId=0;if(!$('shift-form'))return;$('shift-form').reset();$('shift-effective').value=bangkokDate();$('shift-order').value='0';$('shift-active').checked=true;$('shift-save').textContent='เพิ่มกะ';$('shift-cancel-edit').classList.add('hidden');}
function render(){
  if(!state.branchId)return;const branch=state.branch||{};$('shift-branch-note').textContent=`${branch.code||''} · ${branch.name||''}`;$('shift-settings-btn')?.classList.toggle('hidden',false);$('shift-manage-badge').textContent=state.canManage?'แก้ไขได้':'อ่านอย่างเดียว';$('shift-manage-badge').className=`badge ${state.canManage?'badge-ok':'badge-neutral'}`;$('shift-form')?.classList.toggle('readonly-form',!state.canManage);$('shift-form')?.querySelectorAll('input,button').forEach(el=>{if(el.id!=='shift-close')el.disabled=!state.canManage;});
  // Prefer the current-date list for ordinary transitions. If the active shift
  // began yesterday (cross-midnight + version boundary), fall back to the
  // server-resolved currentShift so Effective Date remains correct.
  const current=state.shifts.find(isCurrentShift)||state.backendCurrentShift||null;const pill=$('current-shift-pill');if(pill){pill.classList.remove('hidden');pill.classList.toggle('active',!!current);pill.textContent=current?`${current.name} · ${minuteToTime(current.start_minute)}–${minuteToTime(current.end_minute)}`:'ยังไม่อยู่ในช่วงกะ';}
  $('shift-list').innerHTML=state.shifts.map(s=>`<article class="shift-row ${Number(current?.id)===Number(s.id)?'current':''} ${s.is_active?'':'inactive'}"><div class="shift-row-main"><strong>${esc(s.name)}</strong><span>${minuteToTime(s.start_minute)}–${minuteToTime(s.end_minute)}${Number(s.start_minute)>Number(s.end_minute)?' · ข้ามวัน':''}</span><small>มีผล ${esc(s.effective_from||'-')}${s.effective_to?` ถึง ${esc(s.effective_to)}`:''}</small></div><div class="shift-row-actions">${Number(current?.id)===Number(s.id)?'<span class="shift-now">กะปัจจุบัน</span>':''}${!s.is_active?'<span class="badge badge-neutral">ปิด</span>':''}${state.canManage?`<button class="mini-btn shift-edit" data-id="${s.id}" type="button">แก้ไข</button><button class="mini-btn shift-delete" data-id="${s.id}" type="button">ปิดกะ</button>`:''}</div></article>`).join('')||'<div class="empty-state">ยังไม่ได้ตั้งกะของ HUB/สาขานี้</div>';
  document.querySelectorAll('.shift-edit').forEach(btn=>btn.addEventListener('click',()=>beginEdit(Number(btn.dataset.id))));document.querySelectorAll('.shift-delete').forEach(btn=>btn.addEventListener('click',()=>void removeShift(Number(btn.dataset.id))));
  window.dispatchEvent(new CustomEvent('ms-shift-state',{detail:{branchId:state.branchId,currentShift:current,shifts:state.shifts}}));
}
async function loadShifts(){if(!state.branchId)return;try{$('shift-status')&&($('shift-status').textContent='กำลังอ่านกะ…');const out=await api(`shifts?branch_id=${state.branchId}`);state.shifts=out.data?.shifts||[];state.backendCurrentShift=out.data?.currentShift||null;state.canManage=out.data?.canManage!==false;if($('shift-status'))$('shift-status').textContent=`${state.shifts.length} กะ`;render();}catch(e){if($('shift-status'))$('shift-status').textContent=`โหลดกะไม่สำเร็จ: ${e.message}`;}}
function beginEdit(id){const s=state.shifts.find(x=>Number(x.id)===Number(id));if(!s)return;state.editingId=id;$('shift-name').value=s.name;$('shift-start').value=minuteToTime(s.start_minute);$('shift-end').value=minuteToTime(s.end_minute);$('shift-order').value=String(s.sort_order||0);$('shift-active').checked=!!s.is_active;$('shift-effective').value=bangkokDate();$('shift-save').textContent='บันทึกการเปลี่ยนแปลง';$('shift-cancel-edit').classList.remove('hidden');$('shift-name').focus();}
async function saveShift(event){event.preventDefault();if(!state.canManage)return;const payload={action:state.editingId?'update':'create',id:state.editingId||undefined,name:$('shift-name').value.trim(),startMinute:timeToMinute($('shift-start').value),endMinute:timeToMinute($('shift-end').value),sortOrder:Number($('shift-order').value||0),isActive:$('shift-active').checked,effectiveDate:$('shift-effective').value||bangkokDate()};try{$('shift-status').textContent='กำลังบันทึก…';await api(`shifts?branch_id=${state.branchId}`,{method:'POST',body:JSON.stringify(payload)});resetForm();await loadShifts();$('shift-status').textContent='บันทึกกะแล้ว';}catch(e){$('shift-status').textContent=`บันทึกไม่สำเร็จ: ${e.message}`;}}
async function removeShift(id){if(!state.canManage)return;const s=state.shifts.find(x=>Number(x.id)===Number(id));if(!s||!confirm(`ปิดกะ “${s.name}” ตั้งแต่วันที่เลือกหรือไม่?`))return;try{await api(`shifts?branch_id=${state.branchId}`,{method:'POST',body:JSON.stringify({action:'delete',id,effectiveDate:$('shift-effective')?.value||bangkokDate()})});resetForm();await loadShifts();}catch(e){$('shift-status').textContent=`ปิดกะไม่สำเร็จ: ${e.message}`;}}

installUi();resetForm();
window.addEventListener('ms-branch-ready',event=>{state.branch=event.detail||null;state.branchId=Number(event.detail?.id||0);state.canManage=event.detail?.can_manage_shift!==false;state.backendCurrentShift=null;resetForm();void loadShifts();});
window.addEventListener('ms-session-reset',()=>{state.branchId=0;state.branch=null;state.shifts=[];state.backendCurrentShift=null;$('current-shift-pill')?.classList.add('hidden');$('shift-settings-btn')?.classList.add('hidden');});
setInterval(()=>{if(state.branchId&&state.shifts.length)render();},60_000);
