export const BANDS=['under3','3to6','6to9','9to12','12to16','16to22','22to24','24to48','over48','unknown'];
export const LABELS=['<3','3–6','6–9','9–12','12–16','16–22','22–24','24–48','>48','ไม่ทราบ'];
export const clean=v=>String(v??'').trim().replace(/^\s*(?:(?:\([^)]*\)|（[^）]*）)\s*)+/,'').trim();
const norm=v=>clean(v).toUpperCase().replace(/^\d+\s*/,'').replace(/\s+/g,' ').trim();
export function managerValue(r){const raw=v=>v===null||v===undefined?'':String(v),obj=r||{},full=raw(obj.store_manager_display);if(full)return full;const hasRaw=['store_id','store_name','store_manager_name','store_manager_phone'].some(k=>Object.prototype.hasOwnProperty.call(obj,k));if(hasRaw){const storeLine=`(${raw(obj.store_id)})${raw(obj.store_name)}`;return [storeLine,raw(obj.store_manager_name),raw(obj.store_manager_phone)].filter((v,i)=>i===0||v!=='').join('\n');}return'()';}
export function decodeSnapshotRow(r){const keys=['pno','state_name','store_weight','plan_leave_time','real_arrive_time','pack_num','LastAction_name','LastActionTime','staff_info_phone'];const out=Object.fromEntries(keys.map((k,i)=>[k,r?.[i]??'']));out.store_manager_display=r?.[9]??'';out.store_id=r?.[10]??'';out.store_name=r?.[11]??'';out.store_manager_name=r?.[12]??'';out.store_manager_phone=r?.[13]??'';out.dst_hub_name=r?.[14]??'';out.dst_store_name=r?.[15]??'';return out;}
export function time(v){const raw=String(v||'').trim();return Date.parse(/^\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}/.test(raw)&&!/(Z|[+-]\d{2}:?\d{2})$/i.test(raw)?raw.replace(' ','T')+'+07:00':raw);}
export function band(v,now=Date.now()){const h=(now-time(v))/3600000;if(!Number.isFinite(h)||h<0)return'unknown';return BANDS[[3,6,9,12,16,22,24,48].findIndex((n,i)=>i===7?h<=n:h<n)]||'over48';}
export function ownHubNames(branch){const aliases=Array.isArray(branch?.hub_aliases)?branch.hub_aliases:[],configured=String(branch?.own_hub_name||'').trim(),fallback=[branch?.name,branch?.code];return new Set((configured?[configured,...aliases]:[...fallback,...aliases]).map(norm).filter(Boolean));}
export function route(r,branch){const hub=clean(r?.dst_hub_name),normalized=norm(hub),own=!!normalized&&ownHubNames(branch).has(normalized);return own?{r:'fd',d:clean(r?.dst_store_name)||''}:hub?{r:'lh',d:hub}:{r:'other',d:''};}
export const hasBag=r=>!!String(r.pack_num||'').trim()&&!['-','--'].includes(String(r.pack_num).trim());
export function validAnalytics(a){return !!a?.complete&&a.scanned===a.total&&Array.isArray(a.cells)&&a.cells.reduce((n,c)=>n+Number(c.c||0),0)===a.total;}
function pick(filter,value){if(filter&&typeof filter.has==='function'&&typeof filter.size==='number')return filter.size===0||filter.has(value);if(Array.isArray(filter))return filter.length===0||filter.includes(value);return !filter||filter===value;}
export function match(c,f){return (!f.bands||f.bands.has(c.b))&&pick(f.lh,c.r==='lh'?c.d:null)&&pick(f.fd,c.r==='fd'?c.d:null)&&pick(f.action,c.a)&&pick(f.manager,c.m);}
export function rowCell(r,branch,now){return {...route(r,branch),b:band(r.LastActionTime,now),a:String(r.LastAction_name||'-').trim(),m:managerValue(r)};}
export function rowMatch(r,f,branch,now){return match(rowCell(r,branch,now),f)&&(!f.q||[r.pno,r.pack_num,r.dst_hub_name,r.dst_store_name,r.store_manager_display,r.store_manager_name,r.store_manager_phone,r.store_id,r.store_name,r.LastAction_name,r.state_name].some(x=>String(x||'').toLowerCase().includes(f.q.toLowerCase())))&&(!f.status||r.state_name===f.status);}
export function metrics(cells){return cells.reduce((n,c)=>({count:n.count+Number(c.c||0),weight:n.weight+Number(c.w||0),bagged:n.bagged+Number(c.g||0),overdue:n.overdue+Number(c.o||0),critical:n.critical+Number(c.q||0)}),{count:0,weight:0,bagged:0,overdue:0,critical:0});}
export function groups(cells,key){const m=new Map();for(const c of cells){const name=key(c)||'ไม่ระบุ';const g=m.get(name)||{name,count:0,weight:0,bands:Object.fromEntries(BANDS.map(b=>[b,0])),overdue:0};g.count+=c.c;g.weight+=c.w||0;g.bands[c.b]=(g.bands[c.b]||0)+c.c;g.overdue+=c.o||0;m.set(name,g);}return [...m.values()].sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name,'th'));}
export function bags(rows,branch,now){const m=new Map();for(const r of rows){if(!hasBag(r))continue;const id=String(r.pack_num).trim();const g=m.get(id)||{id,rows:[],dest:new Set(),actions:new Set(),states:new Set(),overdue:false,stale:false,critical:false};g.rows.push(r);const d=route(r,branch);g.dest.add(`${d.r}|${d.d}`);g.actions.add(r.LastAction_name||'-');g.states.add(r.state_name||'-');g.overdue ||= time(r.plan_leave_time)<now;g.stale ||= time(r.LastActionTime)<now-21600000;g.critical ||= band(r.LastActionTime,now)==='over48'&&time(r.plan_leave_time)<now;m.set(id,g);}return [...m.values()].map(g=>({...g,mixed:g.dest.size>1,anomaly:g.dest.size>1||g.actions.size>1||g.states.size>1,destination:g.dest.size===1?[...g.dest][0]:'mixed|ปลายทางปน'}));}
export function riskMatch(r,risk,now){const b=band(r.LastActionTime,now),p=time(r.plan_leave_time);return risk==='all'||risk==='under24'&&BANDS.slice(0,7).includes(b)||risk===b||risk==='missed'&&p<now||risk==='dueSoon'&&p>=now&&p<=now+3600000;}
export function snapshotValid(pages,a){if(!a?.complete||a.scanned!==a.total||pages.length!==a.snapshotPages)return false;const seen=new Set();let count=0;for(let i=0;i<pages.length;i++){const p=pages[i];if(!String(p.cache_key).endsWith(`:p:${String(i+1).padStart(4,'0')}`)||p.source_total!==a.total||!Array.isArray(p.payload)||p.item_count!==p.payload.length)return false;for(const r of p.payload){const id=String(r?.[0]||'').trim();if(!id||seen.has(id))return false;seen.add(id);count++;}}return count===a.total;}
