export const BANDS=['under3','3to6','6to9','9to12','12to16','16to22','22to24','24to48','over48','unknown'];
export const LABELS=['<3','3–6','6–9','9–12','12–16','16–22','22–24','24–48','>48','ไม่ทราบ'];
export const clean=v=>String(v??'').trim().replace(/^\s*(?:(?:\([^)]*\)|（[^）]*）)\s*)+/,'').trim();
export function time(v){const raw=String(v||'').trim();return Date.parse(/^\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}/.test(raw)&&!/(Z|[+-]\d{2}:?\d{2})$/i.test(raw)?raw.replace(' ','T')+'+07:00':raw);}
export function band(v,now=Date.now()){const h=(now-time(v))/3600000;if(!Number.isFinite(h)||h<0)return'unknown';return BANDS[[3,6,9,12,16,22,24,48].findIndex((n,i)=>i===7?h<=n:h<n)]||'over48';}
export function route(r,branch){const hub=clean(r.dst_hub_name),norm=v=>clean(v).toUpperCase().replace(/^\d+\s*/,'').replace(/\s+/g,' ').trim();const code=String(branch?.code||'').trim().replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const own=hub&&((branch?.name&&norm(hub)===norm(branch.name))||(code&&new RegExp(`(^|[^A-Z0-9])${code}(?:_HUB)?([^A-Z0-9]|$)`,'i').test(hub)));return own?{r:'fd',d:clean(r.dst_store_name)||''}:hub?{r:'lh',d:hub}:{r:'other',d:''};}
export const hasBag=r=>!!String(r.pack_num||'').trim()&&!['-','--'].includes(String(r.pack_num).trim());
export function validAnalytics(a){return !!a?.complete&&a.scanned===a.total&&Array.isArray(a.cells)&&a.cells.reduce((n,c)=>n+Number(c.c||0),0)===a.total;}
export function match(c,f){return (!f.bands||f.bands.has(c.b))&&(!f.lh||(c.r==='lh'&&c.d===f.lh))&&(!f.fd||(c.r==='fd'&&c.d===f.fd))&&(!f.action||c.a===f.action)&&(!f.manager||c.m===f.manager);}
export function rowCell(r,branch,now){return {...route(r,branch),b:band(r.real_arrive_time,now),a:String(r.LastAction_name||'-').trim(),m:String(r.store_manager_phone||'-').trim()};}
export function rowMatch(r,f,branch,now){return match(rowCell(r,branch,now),f)&&(!f.q||[r.pno,r.pack_num,r.dst_hub_name,r.dst_store_name,r.store_manager_phone,r.LastAction_name,r.state_name].some(x=>String(x||'').toLowerCase().includes(f.q.toLowerCase())))&&(!f.status||r.state_name===f.status);}
export function metrics(cells){return cells.reduce((n,c)=>({count:n.count+Number(c.c||0),weight:n.weight+Number(c.w||0),bagged:n.bagged+Number(c.g||0),overdue:n.overdue+Number(c.o||0),critical:n.critical+Number(c.q||0)}),{count:0,weight:0,bagged:0,overdue:0,critical:0});}
export function groups(cells,key){const m=new Map();for(const c of cells){const name=key(c)||'ไม่ระบุ';const g=m.get(name)||{name,count:0,weight:0,bands:Object.fromEntries(BANDS.map(b=>[b,0])),overdue:0};g.count+=c.c;g.weight+=c.w||0;g.bands[c.b]=(g.bands[c.b]||0)+c.c;g.overdue+=c.o||0;m.set(name,g);}return [...m.values()].sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name,'th'));}
export function bags(rows,branch,now){const m=new Map();for(const r of rows){if(!hasBag(r))continue;const id=String(r.pack_num).trim();const g=m.get(id)||{id,rows:[],dest:new Set(),actions:new Set(),states:new Set(),overdue:false,stale:false,critical:false};g.rows.push(r);const d=route(r,branch);g.dest.add(`${d.r}|${d.d}`);g.actions.add(r.LastAction_name||'-');g.states.add(r.state_name||'-');g.overdue ||= time(r.plan_leave_time)<now;g.stale ||= time(r.LastActionTime)<now-21600000;g.critical ||= band(r.real_arrive_time,now)==='over48'&&time(r.plan_leave_time)<now;m.set(id,g);}return [...m.values()].map(g=>({...g,mixed:g.dest.size>1,anomaly:g.dest.size>1||g.actions.size>1||g.states.size>1,destination:g.dest.size===1?[...g.dest][0]:'mixed|ปลายทางปน'}));}
export function riskMatch(r,risk,now){const b=band(r.real_arrive_time,now),p=time(r.plan_leave_time);return risk==='all'||risk==='under24'&&BANDS.slice(0,7).includes(b)||risk===b||risk==='missed'&&p<now||risk==='dueSoon'&&p>=now&&p<=now+3600000;}
export function snapshotValid(pages,a){if(!a?.complete||a.scanned!==a.total||pages.length!==a.snapshotPages)return false;const seen=new Set();let count=0;for(let i=0;i<pages.length;i++){const p=pages[i];if(!String(p.cache_key).endsWith(`:p:${String(i+1).padStart(4,'0')}`)||p.source_total!==a.total||!Array.isArray(p.payload)||p.item_count!==p.payload.length)return false;for(const r of p.payload){const id=String(r?.[0]||'').trim();if(!id||seen.has(id))return false;seen.add(id);count++;}}return count===a.total;}
