import {supabase} from './auth-client.js?v=20260906-control-room-v31';

const FUNCTION_BASE='https://afhnfnfbqdqqzrghovfc.supabase.co/functions/v1/ms-parcel-api';
const PUBLISHABLE_KEY='sb_publishable_4GStzbYK3_BhthidusT_hw_DqtzC7qE';
const STORE_KEY='ms-control-room-tools-v1';
const $=(id)=>document.getElementById(id);
const esc=(v)=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const num=(v)=>Number(v||0).toLocaleString('th-TH',{maximumFractionDigits:2});
let branch=null,branchId=0,analytics=null,searchSeq=0,historyTimer;

function readStore(){try{const raw=JSON.parse(localStorage.getItem(STORE_KEY)||'{}');return{saved:Array.isArray(raw.saved)?raw.saved:[],recent:Array.isArray(raw.recent)?raw.recent:[],favorites:Array.isArray(raw.favorites)?raw.favorites:[]};}catch{return{saved:[],recent:[],favorites:[]};}}
function writeStore(value){try{localStorage.setItem(STORE_KEY,JSON.stringify(value));}catch{}}
function selected(id){const el=$(id);return el?[...el.selectedOptions].map(o=>o.value).filter(Boolean):[];}
function captureView(){return{branchId,hash:location.hash||'#dashboard',bands:[...document.querySelectorAll('[data-dashboard-band]:checked')].map(x=>x.dataset.dashboardBand),lh:selected('hub-filter'),fd:selected('branch-filter'),action:selected('ops-action-filter'),manager:selected('manager-phone-filter'),at:new Date().toISOString()};}
function viewFingerprint(v){return JSON.stringify({branchId:v.branchId,bands:v.bands,lh:v.lh,fd:v.fd,action:v.action,manager:v.manager,hash:v.hash});}
function applySelect(id,values){const el=$(id);if(!el)return;const set=new Set(values||[]);let any=false;for(const o of el.options){o.selected=o.value!==''&&set.has(o.value);any||=o.selected;}if(!any){const empty=[...el.options].find(o=>o.value==='');if(empty)empty.selected=true;}el.dispatchEvent(new Event('change',{bubbles:true}));}
function applyView(v){
  if(Number(v.branchId)!==branchId){const branchSelect=$('branch-select');if(branchSelect&&[...branchSelect.options].some(o=>Number(o.value)===Number(v.branchId))){branchSelect.value=String(v.branchId);branchSelect.dispatchEvent(new Event('change',{bubbles:true}));setTimeout(()=>applyView({...v,branchId:Number(v.branchId)}),500);return;}}
  const bands=new Set(v.bands||[]);document.querySelectorAll('[data-dashboard-band]').forEach(x=>{x.checked=bands.has(x.dataset.dashboardBand);x.dispatchEvent(new Event('change',{bubbles:true}));});
  applySelect('hub-filter',v.lh);applySelect('branch-filter',v.fd);applySelect('ops-action-filter',v.action);applySelect('manager-phone-filter',v.manager);window.MSPersistentSelect?.syncAll?.();
  if(v.hash)location.hash=v.hash;
}
function recordRecent(){clearTimeout(historyTimer);historyTimer=setTimeout(()=>{if(!branchId)return;const v=captureView(),store=readStore(),fp=viewFingerprint(v);if(store.recent[0]&&viewFingerprint(store.recent[0])===fp)return;store.recent=[v,...store.recent.filter(x=>viewFingerprint(x)!==fp)].slice(0,8);writeStore(store);renderViews();},800);}

async function edge(route){const{data}=await supabase.auth.getSession();const token=data?.session?.access_token;if(!token)throw new Error('กรุณาเข้าสู่ระบบ');const res=await fetch(`${FUNCTION_BASE}/${route}`,{headers:{Authorization:`Bearer ${token}`,apikey:PUBLISHABLE_KEY},cache:'no-store'}),out=await res.json().catch(()=>({ok:false,message:`HTTP ${res.status}`}));if(!res.ok||!out.ok)throw new Error(out.message||`HTTP ${res.status}`);return out.data||{};}

function install(){
  const actions=document.querySelector('.topbar-actions');
  if(actions&&!$('global-search-btn')){
    const search=document.createElement('button');search.id='global-search-btn';search.className='btn btn-header hidden';search.type='button';search.textContent='ค้นหาทั้งคลัง';search.addEventListener('click',()=>{$('global-search-dialog').showModal();$('global-search-input').focus();});actions.insertBefore(search,$('refresh-btn')||null);
    const tools=document.createElement('button');tools.id='ops-tools-btn';tools.className='btn btn-header hidden';tools.type='button';tools.textContent='เครื่องมือ';tools.addEventListener('click',()=>{$('ops-tools-dialog').showModal();renderViews();void renderCompare();});actions.insertBefore(tools,$('refresh-btn')||null);
  }
  if(!$('global-search-dialog')){
    const d=document.createElement('dialog');d.id='global-search-dialog';d.innerHTML=`<div class="dialog-card global-search-card"><button class="dialog-close" data-close-global type="button">×</button><div class="tool-head"><div><h2>ค้นหาทั้งคลัง</h2><p>เลขพัสดุ · เลขแบ็กกิ้ง · HUB/สาขา · ผู้จัดการ · เบอร์โทร · การดำเนินการล่าสุด</p></div><span class="data-truth-badge ok">ใช้ Snapshot ของระบบ</span></div><input id="global-search-input" class="global-search-input" type="search" placeholder="พิมพ์อย่างน้อย 2 ตัวอักษร"><div id="global-search-note" class="sync-text">ค้นหาจาก Full Snapshot ที่ครบเท่านั้น เพื่อไม่ทำให้ผลลัพธ์ขาดบางหน้า</div><div id="global-search-results" class="global-search-results"></div></div>`;document.body.appendChild(d);d.querySelector('[data-close-global]').addEventListener('click',()=>d.close());$('global-search-input').addEventListener('input',()=>void runSearch());
  }
  if(!$('ops-tools-dialog')){
    const d=document.createElement('dialog');d.id='ops-tools-dialog';d.innerHTML=`<div class="dialog-card ops-tools-card"><button class="dialog-close" data-close-tools type="button">×</button><div class="tool-head"><div><h2>เครื่องมือปฏิบัติการ</h2><p>Saved Views · Recent · Favorites · Compare · Data Quality</p></div><span class="data-truth-badge ok">ไม่เพิ่ม MS reads</span></div><nav class="tool-tabs"><button class="tool-tab active" data-tool-tab="views" type="button">มุมมอง</button><button class="tool-tab" data-tool-tab="compare" type="button">Compare</button><button class="tool-tab" data-tool-tab="quality" type="button">Data Quality</button></nav><section class="tool-pane" data-tool-pane="views"><form id="save-view-form" class="save-view-form"><input id="save-view-name" maxlength="50" placeholder="ชื่อมุมมอง เช่น กะดึก >24h" required><button class="btn btn-accent" type="submit">บันทึกมุมมองปัจจุบัน</button></form><div class="tool-columns"><section><h3>Saved Views</h3><div id="saved-view-list"></div></section><section><h3>Recent</h3><div id="recent-view-list"></div></section><section><h3>Favorites</h3><div id="favorite-list"></div><button id="favorite-current" class="btn btn-header" type="button">เพิ่มปลายทางที่เลือกเป็น Favorite</button></section></div></section><section class="tool-pane hidden" data-tool-pane="compare"><div id="compare-content" class="compare-content"></div></section><section class="tool-pane hidden" data-tool-pane="quality"><div id="quality-note" class="sync-text">กดตรวจเพื่ออ่าน Full Snapshot จาก cache</div><button id="quality-run" class="btn btn-accent" type="button">ตรวจ Data Quality</button><div id="quality-content" class="quality-content"></div></section></div>`;document.body.appendChild(d);d.querySelector('[data-close-tools]').addEventListener('click',()=>d.close());
    d.querySelectorAll('.tool-tab').forEach(btn=>btn.addEventListener('click',()=>{d.querySelectorAll('.tool-tab').forEach(x=>x.classList.toggle('active',x===btn));d.querySelectorAll('[data-tool-pane]').forEach(p=>p.classList.toggle('hidden',p.dataset.toolPane!==btn.dataset.toolTab));if(btn.dataset.toolTab==='compare')void renderCompare();}));
    $('save-view-form').addEventListener('submit',saveView);$('favorite-current').addEventListener('click',favoriteCurrent);$('quality-run').addEventListener('click',()=>void runQuality());
  }
  document.addEventListener('change',(e)=>{if(e.target?.matches?.('[data-dashboard-band],#hub-filter,#branch-filter,#ops-action-filter,#manager-phone-filter'))recordRecent();});
}

async function ensureRows(){if(!window.MSFullSnapshot?.ensureLoaded)throw new Error('โมดูล Full Snapshot ยังไม่พร้อม');return await window.MSFullSnapshot.ensureLoaded();}
async function runSearch(){const input=$('global-search-input'),note=$('global-search-note'),out=$('global-search-results'),q=String(input?.value||'').trim().toLowerCase(),mine=++searchSeq;if(q.length<2){out.innerHTML='';note.textContent='พิมพ์อย่างน้อย 2 ตัวอักษร';return;}note.textContent='กำลังค้นจาก Full Snapshot…';try{const rows=await ensureRows();if(mine!==searchSeq)return;const fields=r=>[r.pno,r.pack_num,r.dst_hub_name,r.dst_store_name,r.store_manager_display,r.store_manager_name,r.store_manager_phone,r.store_id,r.store_name,r.LastAction_name,r.state_name];const matches=rows.filter(r=>fields(r).some(v=>String(v||'').toLowerCase().includes(q))).slice(0,100);note.textContent=`พบ ${num(matches.length)}${matches.length===100?' รายการแรก':''} · Snapshot ${num(rows.length)} ชิ้น`;out.innerHTML=matches.map(r=>`<button class="global-search-row" type="button" data-search-pno="${esc(r.pno)}"><span><strong>${esc(r.pno||'-')}</strong><small>${esc(r.dst_hub_name||'-')} / ${esc(r.dst_store_name||'-')} · ${r.pack_num?`เลขแบ็กกิ้ง ${esc(r.pack_num)}`:'ไม่พบเลขแบ็กกิ้ง'}</small></span><span><b>${esc(r.state_name||'-')}</b><small>${esc(r.LastAction_name||'-')}</small></span></button>`).join('')||'<div class="intel-empty">ไม่พบข้อมูล</div>';out.querySelectorAll('[data-search-pno]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelector('[data-page-nav="parcels"]')?.click();setTimeout(()=>{const search=$('search-input');if(search){search.value=btn.dataset.searchPno;search.dispatchEvent(new Event('input',{bubbles:true}));search.focus();}},80);$('global-search-dialog').close();}));}catch(e){note.textContent=`ยังค้นทั้งคลังไม่ได้: ${e.message}`;out.innerHTML='<div class="intel-empty">ระบบจะไม่ใช้ข้อมูลบางหน้าแทน Full Snapshot เพราะอาจทำให้เข้าใจว่าค้นครบทั้งคลัง</div>';}}

function saveView(event){event.preventDefault();const name=$('save-view-name').value.trim();if(!name)return;const store=readStore(),view={...captureView(),name};store.saved=[view,...store.saved.filter(v=>v.name!==name)].slice(0,30);writeStore(store);event.currentTarget.reset();renderViews();}
function favoriteCurrent(){const store=readStore(),items=[...selected('hub-filter').map(name=>({branchId,route:'lh',name})),...selected('branch-filter').map(name=>({branchId,route:'fd',name}))];if(!items.length)return;const key=x=>`${x.branchId}|${x.route}|${x.name}`;const map=new Map(store.favorites.map(x=>[key(x),x]));items.forEach(x=>map.set(key(x),x));store.favorites=[...map.values()].slice(0,50);writeStore(store);renderViews();}
function renderViews(){const store=readStore(),saved=$('saved-view-list'),recent=$('recent-view-list'),fav=$('favorite-list');if(!saved||!recent||!fav)return;const viewRow=(v,index,type)=>`<div class="stored-view-row"><button type="button" data-view-type="${type}" data-view-index="${index}"><strong>${esc(v.name||new Date(v.at).toLocaleString('th-TH'))}</strong><small>${(v.lh||[]).length} LH · ${(v.fd||[]).length} FD · ${(v.bands||[]).length} ช่วงเวลา</small></button>${type==='saved'?`<button class="stored-delete" type="button" data-delete-view="${index}">×</button>`:''}</div>`;saved.innerHTML=store.saved.map((v,i)=>viewRow(v,i,'saved')).join('')||'<div class="intel-empty">ยังไม่มี Saved View</div>';recent.innerHTML=store.recent.map((v,i)=>viewRow(v,i,'recent')).join('')||'<div class="intel-empty">ยังไม่มี Recent View</div>';fav.innerHTML=store.favorites.map((v,i)=>`<div class="stored-view-row"><button type="button" data-favorite-index="${i}"><strong>${v.route.toUpperCase()} · ${esc(v.name)}</strong><small>HUB/สาขาที่บันทึกไว้</small></button><button class="stored-delete" type="button" data-delete-favorite="${i}">×</button></div>`).join('')||'<div class="intel-empty">ยังไม่มี Favorite</div>';
  document.querySelectorAll('[data-view-type]').forEach(btn=>btn.addEventListener('click',()=>{const s=readStore(),v=s[btn.dataset.viewType]?.[Number(btn.dataset.viewIndex)];if(v)applyView(v);}));document.querySelectorAll('[data-delete-view]').forEach(btn=>btn.addEventListener('click',()=>{const s=readStore();s.saved.splice(Number(btn.dataset.deleteView),1);writeStore(s);renderViews();}));document.querySelectorAll('[data-favorite-index]').forEach(btn=>btn.addEventListener('click',()=>{const v=readStore().favorites[Number(btn.dataset.favoriteIndex)];if(!v)return;applySelect(v.route==='lh'?'hub-filter':'branch-filter',[v.name]);}));document.querySelectorAll('[data-delete-favorite]').forEach(btn=>btn.addEventListener('click',()=>{const s=readStore();s.favorites.splice(Number(btn.dataset.deleteFavorite),1);writeStore(s);renderViews();}));}

function metricDiff(label,a,b){const d=Number(a||0)-Number(b||0);return`<div class="compare-row"><span>${label}</span><b>${num(b)} → ${num(a)}</b><strong class="${d>0?'up':d<0?'down':''}">${d>0?'+':''}${num(d)}</strong></div>`;}
async function renderCompare(){const el=$('compare-content');if(!el||!branchId)return;el.innerHTML='<div class="intel-empty">กำลังอ่านข้อมูล Compare จาก cache/aggregate…</div>';try{const shift=await edge(`shift-summary?branch_id=${branchId}`),changes=analytics?.changes||{},cur=shift.current?.latest_metrics||{},start=shift.current?.start_metrics||{},prev=shift.previous?.latest_metrics||{},same=(shift.history||[]).find(x=>x.shift_logical_id===shift.current?.shift_logical_id&&x.shift_date<shift.current?.shift_date)?.latest_metrics||null;el.innerHTML=`<section class="compare-block"><h3>ตอนนี้ vs Snapshot ก่อน</h3>${changes.available?['totalDelta','fdDelta','lhDelta','over24Delta','over48Delta'].map((k,i)=>`<div class="compare-row"><span>${['คงคลัง','FD','LH','≥24ชม.','>48ชม.'][i]}</span><b>${changes[k]>0?'+':''}${num(changes[k])}</b><small>${Number(changes.elapsedMinutes||0).toFixed(0)} นาที</small></div>`).join(''):'<div class="intel-empty">ต้องมี Full Snapshot ที่ครบอย่างน้อย 2 รอบ</div>'}</section><section class="compare-block"><h3>กะนี้: ต้นกะ vs ล่าสุด</h3>${shift.current?['total','fd','lh','over24','over48','uniqueBags'].map((k,i)=>metricDiff(['คงคลัง','FD','LH','≥24ชม.','>48ชม.','เลขแบ็กกิ้ง'][i],cur[k],start[k])).join(''):'<div class="intel-empty">ยังไม่มี aggregate ของกะนี้</div>'}</section><section class="compare-block"><h3>กะนี้ vs กะก่อน</h3>${shift.previous?['total','fd','lh','over24','over48'].map((k,i)=>metricDiff(['คงคลัง','FD','LH','≥24ชม.','>48ชม.'][i],cur[k],prev[k])).join(''):'<div class="intel-empty">ยังไม่มีกะก่อนหน้า</div>'}</section><section class="compare-block"><h3>กะเดียวกัน vs วันก่อน</h3>${same?['total','fd','lh','over24','over48'].map((k,i)=>metricDiff(['คงคลัง','FD','LH','≥24ชม.','>48ชม.'][i],cur[k],same[k])).join(''):'<div class="intel-empty">ยังไม่มีประวัติกะ logical เดียวกันของวันก่อน</div>'}</section>`;}catch(e){el.innerHTML=`<div class="intel-empty">Compare ยังไม่พร้อม: ${esc(e.message)}</div>`;}}

function validTime(v){if(!String(v||'').trim())return true;const raw=String(v).trim(),normalized=/^\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}/.test(raw)&&!/(Z|[+-]\d{2}:?\d{2})$/i.test(raw)?raw.replace(' ','T')+'+07:00':raw;return Number.isFinite(Date.parse(normalized));}
async function runQuality(){const note=$('quality-note'),out=$('quality-content');note.textContent='กำลังตรวจ Full Snapshot…';try{const rows=await ensureRows(),packDest=new Map();let missingArrival=0,missingHub=0,missingStore=0,missingManager=0,badTimestamp=0;for(const r of rows){if(!String(r.real_arrive_time||'').trim())missingArrival++;if(!String(r.dst_hub_name||'').trim())missingHub++;if(!String(r.dst_store_name||'').trim())missingStore++;if(!String(r.store_manager_name||'').trim()&&!String(r.store_manager_phone||'').trim())missingManager++;if(!validTime(r.LastActionTime)||!validTime(r.plan_leave_time)||!validTime(r.real_arrive_time))badTimestamp++;const pack=String(r.pack_num||'').trim();if(pack&&!['-','--'].includes(pack)){const dest=`${r.dst_hub_name||''}|${r.dst_store_name||''}`;if(!packDest.has(pack))packDest.set(pack,new Set());packDest.get(pack).add(dest);}}const conflict=[...packDest.values()].filter(s=>s.size>1).length;note.textContent=`ตรวจ ${num(rows.length)} ชิ้นจาก Full Snapshot`;out.innerHTML=`<div class="quality-grid"><article><span>ไม่พบเวลาถึง</span><strong>${num(missingArrival)}</strong><small>ข้อมูลต้นทาง</small></article><article><span>ไม่พบ HUB ปลายทาง</span><strong>${num(missingHub)}</strong><small>ต้องตรวจสอบ</small></article><article><span>ไม่พบสาขาปลายทาง</span><strong>${num(missingStore)}</strong><small>ต้องตรวจสอบ</small></article><article><span>ไม่พบข้อมูลผู้จัดการ</span><strong>${num(missingManager)}</strong><small>ข้อมูลต้นทาง</small></article><article><span>Timestamp ผิดรูปแบบ</span><strong>${num(badTimestamp)}</strong><small>Data Quality</small></article><article><span>เลขแบ็กกิ้งปลายทางขัดแย้ง</span><strong>${num(conflict)}</strong><small>ควรตรวจ</small></article></div>`;}catch(e){note.textContent=`ตรวจไม่ได้: ${e.message}`;out.innerHTML='<div class="intel-empty">Data Quality ที่ต้องใช้ทั้งคลังจะไม่คำนวณจาก Snapshot ที่ไม่ครบ</div>';}}

install();renderViews();
window.addEventListener('ms-branch-ready',(event)=>{branch=event.detail||null;branchId=Number(branch?.id||0);$('global-search-btn')?.classList.toggle('hidden',!branchId);$('ops-tools-btn')?.classList.toggle('hidden',!branchId);renderViews();});
window.addEventListener('ms-full-analytics',(event)=>{if(Number(event.detail?.branchId||0)!==branchId)return;analytics=event.detail||null;if($('ops-tools-dialog')?.open)void renderCompare();});
window.addEventListener('ms-session-reset',()=>{branch=null;branchId=0;analytics=null;$('global-search-btn')?.classList.add('hidden');$('ops-tools-btn')?.classList.add('hidden');});
