import './analytics-client.js?v=20260906-1';

const $=(id)=>document.getElementById(id);
const fmt=new Intl.NumberFormat('th-TH');
let cachedRows=[],cacheSourceBranch='',scheduled=false,rebuilding=false,fullAnalytics=window.__MS_FULL_ANALYTICS||null;
const BAND_KEYS=['under3','3to6','6to9','9to12','12to16','16to22','22to24','24to48','over48'];

function esc(v){return String(v??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function text(el){return String(el?.textContent??'').trim();}
function cleanDestination(value){const raw=String(value??'').trim();if(!raw)return'';return raw.replace(/^\s*(?:(?:\([^)]*\)|（[^）]*）)\s*)+/,'').trim()||raw;}
function parseMsTime(value){const raw=String(value??'').trim();if(!raw||raw==='-'||raw==='--')return NaN;let normalized=raw;if(/^\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}/.test(raw)&&!/(?:Z|[+-]\d{2}:?\d{2})$/i.test(raw))normalized=raw.replace(' ','T')+'+07:00';const n=Date.parse(normalized);return Number.isFinite(n)?n:NaN;}
function ageBand(arrived,now=Date.now()){const t=parseMsTime(arrived);if(!Number.isFinite(t)||now<t)return'unknown';const h=(now-t)/3600000;if(h<3)return'under3';if(h<6)return'3to6';if(h<9)return'6to9';if(h<12)return'9to12';if(h<16)return'12to16';if(h<22)return'16to22';if(h<24)return'22to24';if(h<=48)return'24to48';return'over48';}
function parseWeightKg(value){const n=Number.parseFloat(String(value??'').replace(/,/g,'').trim());return Number.isFinite(n)?n:0;}
function sourceBranchKey(){return`${String($('branch-select')?.value||'')}|${text($('branch-select')?.selectedOptions?.[0])}`;}
function sourceAliases(){const[codePart,...rest]=text($('branch-select')?.selectedOptions?.[0]).split('·');return{code:String(codePart||'').trim().toUpperCase(),name:String(rest.join('·')||'').trim()};}
function normalizeName(value){return cleanDestination(value).toUpperCase().replace(/^\d+\s*/,'').replace(/\s+/g,' ').trim();}
function isOwnHub(value){const raw=cleanDestination(value);if(!raw)return false;const{code,name}=sourceAliases();if(name&&normalizeName(raw)===normalizeName(name))return true;if(!code)return false;const escaped=code.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return new RegExp(`(^|[^A-Z0-9])${escaped}(?:_HUB)?([^A-Z0-9]|$)`,'i').test(raw.toUpperCase());}

function parseTableRows(){return[...document.querySelectorAll('#table-body tr')].map((tr,index)=>{const c=tr.cells,bagRaw=text(c[5]);return{tr,index,pno:text(c[0]),parcelState:text(c[1]),plan:text(c[4]?.querySelector('.cell-stack > span')),arrived:text(c[4]?.querySelector('.cell-stack > small')),bag:bagRaw&&bagRaw!=='-'&&bagRaw!=='--'?bagRaw:'',latestAction:text(c[7]?.querySelector('.cell-stack > span'))||'-',latestTime:text(c[7]?.querySelector('.cell-stack > small'))||'-',operatorName:text(c[8]?.querySelector('.cell-stack > span'))||'-',operatorPhone:text(c[8]?.querySelector('.cell-stack > small'))||'-',hubRaw:text(c[9]?.querySelector('.cell-stack > span')),branchRaw:text(c[9]?.querySelector('.cell-stack > small')),hub:cleanDestination(text(c[9]?.querySelector('.cell-stack > span')))||'-',branch:cleanDestination(text(c[9]?.querySelector('.cell-stack > small')))||'-',weightKg:parseWeightKg(text(c[3]?.querySelector('.cell-stack > small')))};}).filter((r)=>r.pno);}
function filtersNeutral(){return!String($('search-input')?.value||'').trim()&&!String($('status-filter')?.value||'');}
function updateCache(){const key=sourceBranchKey();if(key!==cacheSourceBranch){cacheSourceBranch=key;cachedRows=[];}const rows=parseTableRows();if(rows.length&&(filtersNeutral()||!cachedRows.length))cachedRows=rows;return cachedRows.length?cachedRows:rows;}
function selectedBands(){return new Set([...document.querySelectorAll('[data-dashboard-band]')].filter((x)=>x.checked).map((x)=>x.dataset.dashboardBand));}
function allTimes(){return selectedBands().size===BAND_KEYS.length;}
function selectedLH(){return String($('hub-filter')?.value||'');}
function selectedFD(){return String($('branch-filter')?.value||'');}
function selectedAction(){return String($('ops-action-filter')?.value||'');}
function hasFull(){return!!fullAnalytics?.complete&&Array.isArray(fullAnalytics?.cells);}

function globalRows({ignoreAction=false}={}){const bands=selectedBands(),lh=selectedLH(),fd=selectedFD(),action=selectedAction();return updateCache().filter((r)=>{if(!allTimes()&&!bands.has(ageBand(r.arrived)))return false;if(lh&&(!(!isOwnHub(r.hubRaw)&&r.hub===lh)))return false;if(fd&&(!(isOwnHub(r.hubRaw)&&r.branch===fd)))return false;if(!ignoreAction&&action&&r.latestAction!==action)return false;return true;});}
function filteredCells({ignoreAction=false,ignoreDestination=false}={}){if(!hasFull())return[];const bands=selectedBands(),lh=selectedLH(),fd=selectedFD(),action=selectedAction();return fullAnalytics.cells.filter((c)=>{if(!allTimes()&&!bands.has(c.b))return false;if(!ignoreDestination){if(lh&&(c.r!=='lh'||c.d!==lh))return false;if(fd&&(c.r!=='fd'||c.d!==fd))return false;}if(!ignoreAction&&action&&c.a!==action)return false;return true;});}
function cellMetrics(cells){return cells.reduce((m,c)=>{m.count+=Number(c.c||0);m.weight+=Number(c.w||0);m.bagged+=Number(c.g||0);m.overdue+=Number(c.o||0);m.critical+=Number(c.q||0);return m;},{count:0,weight:0,bagged:0,overdue:0,critical:0});}
function groupCells(cells,keyFn){const map=new Map();for(const c of cells){const key=String(keyFn(c)||'-'),v=map.get(key)||{name:key,count:0,weight:0,bagged:0,latest:0};v.count+=Number(c.c||0);v.weight+=Number(c.w||0);v.bagged+=Number(c.g||0);v.latest=Math.max(v.latest,Number(c.t||0));map.set(key,v);}return[...map.values()].sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name,'th'));}
function fmtKg(v){return Number(v||0).toLocaleString('th-TH',{maximumFractionDigits:2});}
function latestText(ms){return ms?new Date(ms).toLocaleString('th-TH'):'-';}

function setSelectOptions(select,values,keep){if(!select)return;const desired=[['','ทั้งหมด'],...values.map((v)=>[v,v])],current=[...select.options].map((o)=>[o.value,text(o)]);if(JSON.stringify(current)!==JSON.stringify(desired))select.innerHTML=desired.map(([value,label])=>`<option value="${esc(value)}">${esc(label)}</option>`).join('');select.value=values.includes(keep)?keep:'';}
function rebuildFilters(){if(rebuilding)return;rebuilding=true;try{const keepLH=selectedLH(),keepFD=selectedFD(),keepAction=selectedAction();let lhs=[],fds=[],actions=[];if(hasFull()){lhs=(fullAnalytics.lh||[]).map((x)=>cleanDestination(x.name)).filter(Boolean);fds=(fullAnalytics.fd||[]).map((x)=>cleanDestination(x.name)).filter(Boolean);actions=(fullAnalytics.actions||[]).map((x)=>String(x.name||'')).filter(Boolean);}else{const rows=updateCache();lhs=[...new Set(rows.filter((r)=>!isOwnHub(r.hubRaw)).map((r)=>r.hub).filter((x)=>x&&x!=='-'))];fds=[...new Set(rows.filter((r)=>isOwnHub(r.hubRaw)).map((r)=>r.branch).filter((x)=>x&&x!=='-'))];actions=[...new Set(rows.map((r)=>r.latestAction).filter(Boolean))];}lhs.sort((a,b)=>a.localeCompare(b,'th'));fds.sort((a,b)=>a.localeCompare(b,'th'));actions.sort((a,b)=>a.localeCompare(b,'th'));setSelectOptions($('hub-filter'),lhs,keepLH);setSelectOptions($('branch-filter'),fds,keepFD);setSelectOptions($('ops-action-filter'),actions,keepAction);}finally{rebuilding=false;}}

function applyDetailFilters(){const rows=parseTableRows(),lh=selectedLH(),fd=selectedFD(),action=selectedAction(),bands=selectedBands(),timeActive=!allTimes();const cards=[...document.querySelectorAll('#mobile-cards .mobile-card')];rows.forEach((r)=>{const hide=(timeActive&&!bands.has(ageBand(r.arrived)))||(lh&&(!(!isOwnHub(r.hubRaw)&&r.hub===lh)))||(fd&&(!(isOwnHub(r.hubRaw)&&r.branch===fd)))||(action&&r.latestAction!==action);r.tr.classList.toggle('ops-filter-hidden',hide);cards[r.index]?.classList.toggle('ops-filter-hidden',hide);});}

function countBy(rows,getter){const map=new Map();for(const row of rows){const key=String(getter(row)||'-');map.set(key,(map.get(key)||0)+1);}return[...map.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0],'th'));}
function latestTime(rows){let best=null;for(const row of rows){const n=parseMsTime(row.latestTime);if(Number.isFinite(n)&&(!best||n>best.n))best={n,text:row.latestTime};}return best?.text||'-';}

function renderStatusPage(){const detail=globalRows();if(hasFull()){const cells=filteredCells(),groups=groupCells(cells,(c)=>c.a),metrics=cellMetrics(cells);$('ops-status-total').textContent=fmt.format(metrics.count);$('ops-status-types').textContent=fmt.format(groups.length);$('ops-status-table').innerHTML=groups.length?groups.map((g)=>`<tr><td>${esc(g.name)}</td><td>${fmt.format(g.count)}</td><td>${metrics.count?(g.count/metrics.count*100).toFixed(1):'0.0'}%</td><td>${esc(latestText(g.latest))}</td></tr>`).join(''):'<tr><td colspan="4">-</td></tr>';}else{const groups=countBy(detail,(r)=>r.latestAction);$('ops-status-total').textContent=text($('m-total'))||'0';$('ops-status-types').textContent='-';$('ops-status-table').innerHTML='<tr><td colspan="4">รอข้อมูลรวม</td></tr>';}
  $('ops-status-detail').innerHTML=detail.length?detail.map((r)=>`<tr><td>${esc(r.pno)}</td><td>${esc(r.latestAction)}</td><td>${esc(r.latestTime)}</td><td>${esc(r.operatorPhone)}</td><td>${esc(isOwnHub(r.hubRaw)?'-':r.hub)}</td><td>${esc(isOwnHub(r.hubRaw)?r.branch:'-')}</td></tr>`).join(''):'<tr><td colspan="6">-</td></tr>';}

function renderWeightPage(){if(hasFull()){const cells=filteredCells(),metrics=cellMetrics(cells),fdGroups=groupCells(cells.filter((c)=>c.r==='fd'),(c)=>c.d),lhGroups=groupCells(cells.filter((c)=>c.r==='lh'),(c)=>c.d);$('ops-weight-parcels').textContent=fmt.format(metrics.count);$('ops-weight-total').textContent=`${fmtKg(metrics.weight)} kg`;$('ops-weight-avg').textContent=`${fmtKg(metrics.count?metrics.weight/metrics.count:0)} kg`;$('ops-weight-branches').textContent=fmt.format(fdGroups.length);$('ops-weight-lh-count').textContent=fmt.format(lhGroups.length);$('ops-fd-table').innerHTML=fdGroups.length?fdGroups.map((g)=>`<tr><td>${esc(g.name)}</td><td>${fmt.format(g.count)}</td><td>${fmtKg(g.weight)}</td><td>${fmtKg(g.count?g.weight/g.count:0)}</td></tr>`).join(''):'<tr><td colspan="4">-</td></tr>';$('ops-lh-table').innerHTML=lhGroups.length?lhGroups.map((g)=>`<tr><td>${esc(g.name)}</td><td>${fmt.format(g.count)}</td><td>${fmtKg(g.weight)}</td><td>${fmtKg(g.count?g.weight/g.count:0)}</td></tr>`).join(''):'<tr><td colspan="4">-</td></tr>';return;}
  $('ops-weight-parcels').textContent=text($('m-total'))||'0';$('ops-weight-total').textContent='-';$('ops-weight-avg').textContent='-';$('ops-weight-branches').textContent='-';$('ops-weight-lh-count').textContent='-';$('ops-fd-table').innerHTML='<tr><td colspan="4">รอข้อมูลรวม</td></tr>';$('ops-lh-table').innerHTML='<tr><td colspan="4">รอข้อมูลรวม</td></tr>';}

function bagGroups(rows){const map=new Map();for(const r of rows){if(!r.bag)continue;const g=map.get(r.bag)||{bag:r.bag,rows:[]};g.rows.push(r);map.set(r.bag,g);}return[...map.values()].map((g)=>{const destinations=new Set(g.rows.map((r)=>`${r.hubRaw}|${r.branchRaw}`)),actions=new Set(g.rows.map((r)=>r.latestAction)),states=new Set(g.rows.map((r)=>r.parcelState)),now=Date.now(),planOverdue=g.rows.some((r)=>{const n=parseMsTime(r.plan);return Number.isFinite(n)&&now>n;}),stale6h=g.rows.some((r)=>{const n=parseMsTime(r.latestTime);return Number.isFinite(n)&&now-n>6*3600000;}),critical=g.rows.some((r)=>{const n=parseMsTime(r.plan);return ageBand(r.arrived,now)==='over48'&&Number.isFinite(n)&&now>n;});return{...g,mixedDestination:destinations.size>1,mixedAction:actions.size>1,mixedState:states.size>1,planOverdue,stale6h,critical};});}
function bagIssueMatch(g,issue){if(!issue||issue==='all')return true;if(issue==='anomaly')return g.mixedDestination||g.mixedAction||g.mixedState;if(issue==='mixedDestination')return g.mixedDestination;if(issue==='mixedAction')return g.mixedAction;if(issue==='mixedState')return g.mixedState;if(issue==='planOverdue')return g.planOverdue;if(issue==='stale6h')return g.stale6h;if(issue==='critical')return g.critical;return true;}
function currentBagRows(){let base=globalRows().filter((r)=>r.bag);const search=String($('bag-search')?.value||'').trim().toLowerCase(),issue=String($('bag-issue-filter')?.value||'all');if(search)base=base.filter((r)=>r.bag.toLowerCase().includes(search));if(issue!=='all'){const allowed=new Set(bagGroups(base).filter((g)=>bagIssueMatch(g,issue)).map((g)=>g.bag));base=base.filter((r)=>allowed.has(r.bag));}return base;}
function renderBagDetail(){const pageRows=currentBagRows(),pageGroups=bagGroups(globalRows().filter((r)=>r.bag));if(hasFull()){const cells=filteredCells(),metrics=cellMetrics(cells);$('bag-parcels').textContent=fmt.format(metrics.bagged);$('bag-count').textContent=(allTimes()&&!selectedLH()&&!selectedFD()&&!selectedAction())?fmt.format(Number(fullAnalytics.uniqueBags||0)):'-';}else{$('bag-parcels').textContent='-';$('bag-count').textContent='-';}$('bag-anomaly').textContent=fmt.format(pageGroups.filter((g)=>g.mixedDestination||g.mixedAction||g.mixedState).length);$('bag-plan-overdue').textContent=fmt.format(pageGroups.filter((g)=>g.planOverdue).length);$('bag-stale').textContent=fmt.format(pageGroups.filter((g)=>g.stale6h).length);$('ops-bag-detail').innerHTML=pageRows.length?pageRows.map((r)=>`<tr><td>${esc(isOwnHub(r.hubRaw)?'-':r.hub)}</td><td>${esc(isOwnHub(r.hubRaw)?r.branch:'-')}</td><td>${esc(r.bag)}</td><td>${esc(r.pno)}</td><td>${esc(r.operatorPhone)}</td><td>${esc(r.latestTime)}</td></tr>`).join(''):'<tr><td colspan="6">-</td></tr>';$('ops-bag-detail-count').textContent=fmt.format(pageRows.length);}
async function copyBagRows(){const rows=currentBagRows();if(!rows.length)return;const output=['LH ปลายทาง | FD ปลายทาง | เลขแบ็กกิ้ง | เลขพัสดุ | เบอร์ผู้ดำเนินการล่าสุด | เวลาดำเนินการล่าสุด',...rows.map((r)=>`${isOwnHub(r.hubRaw)?'-':r.hub} | ${isOwnHub(r.hubRaw)?r.branch:'-'} | ${r.bag} | ${r.pno} | ${r.operatorPhone} | ${r.latestTime}`)].join('\n');try{if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(output);else{const ta=document.createElement('textarea');ta.value=output;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();}}catch(_){}}

function renderFullDashboard(){if(!hasFull())return;const cells=filteredCells(),metrics=cellMetrics(cells),timeGroups=groupCells(cells,(c)=>c.b),lhGroups=groupCells(cells.filter((c)=>c.r==='lh'),(c)=>c.d),fdGroups=groupCells(cells.filter((c)=>c.r==='fd'),(c)=>c.d),actionGroups=groupCells(cells,(c)=>c.a),bandLabels={under3:'<3 ชม.',3to6:'3–6 ชม.',6to9:'6–9 ชม.',9to12:'9–12 ชม.',12to16:'12–16 ชม.',16to22:'16–22 ชม.',22to24:'22–24 ชม.',24to48:'24–48 ชม.',over48:'>48 ชม.',unknown:'อายุไม่ทราบ'};$('dash-loaded').textContent=fmt.format(Number(fullAnalytics.total||0));$('dash-selected').textContent=fmt.format(metrics.count);$('dash-over-plan').textContent=fmt.format(metrics.overdue);$('dash-bagged').textContent=fmt.format(metrics.bagged);$('dash-critical').textContent=fmt.format(metrics.critical);if($('dashboard-selection-note'))$('dashboard-selection-note').textContent=`${fmt.format(metrics.count)} / ${fmt.format(Number(fullAnalytics.total||0))} รายการ`;const renderList=(id,groups,labelFn=(x)=>x.name)=>{const el=$(id);if(!el)return;el.innerHTML=groups.slice(0,12).map((g)=>`<div class="summary-row"><div><span>${esc(labelFn(g))}</span><strong>${fmt.format(g.count)}</strong></div><i><b style="width:${metrics.count?Math.max(3,Math.round(g.count/metrics.count*100)):0}%"></b></i></div>`).join('')||'<div class="summary-empty">-</div>';};renderList('dashboard-time-summary',timeGroups,(g)=>bandLabels[g.name]||g.name);renderList('dashboard-hub-summary',lhGroups);renderList('dashboard-branch-summary',fdGroups);renderList('dashboard-action-summary',actionGroups);}

function renderAll(){rebuildFilters();applyDetailFilters();renderStatusPage();renderWeightPage();renderBagDetail();setTimeout(renderFullDashboard,0);}
function scheduleRender(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;renderAll();});}
function pageSection(name,title,body){const section=document.createElement('section');section.className='page-view hidden';section.dataset.pageView=name;section.innerHTML=`<div class="page-title"><h2>${title}</h2></div>${body}`;return section;}
function ensureStructure(){const css=document.createElement('link');css.rel='stylesheet';css.href='ops.css?v=20260906-1';document.head.appendChild(css);const nav=document.querySelector('.app-nav-inner');if(nav&&!nav.querySelector('[data-page-nav="status"]')){const statusBtn=document.createElement('button');statusBtn.className='app-nav-btn';statusBtn.type='button';statusBtn.dataset.pageNav='status';statusBtn.textContent='สถานะพัสดุ';nav.insertBefore(statusBtn,nav.querySelector('[data-page-nav="backlog"]'));const weightBtn=document.createElement('button');weightBtn.className='app-nav-btn';weightBtn.type='button';weightBtn.dataset.pageNav='weight';weightBtn.textContent='น้ำหนักสาขา';nav.insertBefore(weightBtn,nav.querySelector('[data-page-nav="bagging"]'));}
  const main=document.querySelector('main.app-shell'),backlog=document.querySelector('[data-page-view="backlog"]'),bagging=document.querySelector('[data-page-view="bagging"]');
  if(main&&backlog&&!document.querySelector('[data-page-view="status"]'))main.insertBefore(pageSection('status','สถานะพัสดุ',`<div class="ops-metric-grid"><article><span>พัสดุทั้งหมด</span><strong id="ops-status-total">0</strong></article><article><span>การดำเนินการล่าสุด</span><strong id="ops-status-types">0</strong></article></div><section class="panel ops-panel"><h3>สรุปการดำเนินการล่าสุด</h3><div class="ops-table-scroll compact"><table class="ops-table"><thead><tr><th>การดำเนินการล่าสุด</th><th>จำนวน</th><th>สัดส่วน</th><th>เวลาล่าสุด</th></tr></thead><tbody id="ops-status-table"></tbody></table></div></section><section class="panel ops-panel"><div class="ops-panel-head"><h3>รายการพัสดุ</h3><span>หน้าปัจจุบัน</span></div><div class="ops-table-scroll"><table class="ops-table"><thead><tr><th>เลขพัสดุ</th><th>การดำเนินการล่าสุด</th><th>เวลา</th><th>เบอร์ผู้ดำเนินการ</th><th>LH ปลายทาง</th><th>FD ปลายทาง</th></tr></thead><tbody id="ops-status-detail"></tbody></table></div></section>`),backlog);
  if(main&&bagging&&!document.querySelector('[data-page-view="weight"]'))main.insertBefore(pageSection('weight','น้ำหนักสาขา',`<div class="ops-metric-grid five"><article><span>พัสดุทั้งหมด</span><strong id="ops-weight-parcels">0</strong></article><article><span>น้ำหนักรวม</span><strong id="ops-weight-total">0 kg</strong></article><article><span>เฉลี่ย/ชิ้น</span><strong id="ops-weight-avg">0 kg</strong></article><article><span>FD</span><strong id="ops-weight-branches">0</strong></article><article><span>LH</span><strong id="ops-weight-lh-count">0</strong></article></div><section class="panel ops-panel"><h3>FD ปลายทาง</h3><div class="ops-table-scroll"><table class="ops-table"><thead><tr><th>FD ปลายทาง</th><th>จำนวนพัสดุ</th><th>น้ำหนักรวม kg</th><th>เฉลี่ย kg</th></tr></thead><tbody id="ops-fd-table"></tbody></table></div></section><section class="panel ops-panel"><h3>LH ปลายทาง</h3><div class="ops-table-scroll"><table class="ops-table"><thead><tr><th>LH ปลายทาง</th><th>จำนวนพัสดุ</th><th>น้ำหนักรวม kg</th><th>เฉลี่ย kg</th></tr></thead><tbody id="ops-lh-table"></tbody></table></div></section>`),bagging);
  const globalGrid=document.querySelector('.global-destination-grid');if(globalGrid&&!$('ops-action-filter')){const label=document.createElement('label');label.innerHTML='<span>การดำเนินการล่าสุด</span><select id="ops-action-filter"><option value="">ทั้งหมด</option></select>';globalGrid.insertBefore(label,globalGrid.querySelector('.selected-inline'));}
  for(const id of['bag-mode','bag-action-filter','bag-hub-filter','bag-branch-filter'])$(id)?.closest('label')?.classList.add('hidden');if(bagging&&!$('ops-bag-detail')){const detail=document.createElement('section');detail.className='panel ops-panel ops-bag-detail-panel';detail.innerHTML=`<div class="ops-panel-head"><h3>รายการแบ็กกิ้ง</h3><span><b id="ops-bag-detail-count">0</b> รายการในหน้า</span></div><div class="ops-table-scroll"><table class="ops-table"><thead><tr><th>LH ปลายทาง</th><th>FD ปลายทาง</th><th>เลขแบ็กกิ้ง</th><th>เลขพัสดุ</th><th>เบอร์ผู้ดำเนินการล่าสุด</th><th>เวลาที่ดำเนินการล่าสุด</th></tr></thead><tbody id="ops-bag-detail"></tbody></table></div>`;bagging.querySelector('.bag-panel')?.after(detail);}
  const anomaly=$('bag-anomaly')?.closest('article')?.querySelector('span');if(anomaly)anomaly.textContent='ผิดปกติในหน้า';const overdue=$('bag-plan-overdue')?.closest('article')?.querySelector('span');if(overdue)overdue.textContent='เกินเวลาแผนในหน้า';const stale=$('bag-stale')?.closest('article')?.querySelector('span');if(stale)stale.textContent='ไม่อัปเดต >6ชม. ในหน้า';}
ensureStructure();

document.addEventListener('DOMContentLoaded',()=>{const tbody=$('table-body');if(tbody)new MutationObserver(scheduleRender).observe(tbody,{childList:true});const destinationChange=(id,e)=>{e.stopImmediatePropagation();if(id==='hub-filter'&&$('hub-filter').value)$('branch-filter').value='';if(id==='branch-filter'&&$('branch-filter').value)$('hub-filter').value='';scheduleRender();};$('hub-filter')?.addEventListener('change',(e)=>destinationChange('hub-filter',e),true);$('branch-filter')?.addEventListener('change',(e)=>destinationChange('branch-filter',e),true);$('ops-action-filter')?.addEventListener('change',scheduleRender);$('bag-issue-filter')?.addEventListener('change',scheduleRender);$('bag-search')?.addEventListener('input',scheduleRender);document.querySelectorAll('[data-dashboard-band]').forEach((el)=>el.addEventListener('change',scheduleRender));$('copy-bag-btn')?.addEventListener('click',(e)=>{e.stopImmediatePropagation();void copyBagRows();},{capture:true});$('branch-select')?.addEventListener('change',()=>{cachedRows=[];cacheSourceBranch=sourceBranchKey();fullAnalytics=null;if($('hub-filter'))$('hub-filter').value='';if($('branch-filter'))$('branch-filter').value='';if($('ops-action-filter'))$('ops-action-filter').value='';setTimeout(scheduleRender,0);});window.addEventListener('ms-full-analytics',(e)=>{fullAnalytics=e.detail||null;scheduleRender();});renderAll();});
