const $=(id)=>document.getElementById(id);
const fmt=new Intl.NumberFormat('th-TH');
const PAGE_IDS=new Set(['dashboard','parcels','status','backlog','weight','bagging']);
const TIME_BANDS=[['under3','<3 ชม.'],['3to6','3–6 ชม.'],['6to9','6–9 ชม.'],['9to12','9–12 ชม.'],['12to16','12–16 ชม.'],['16to22','16–22 ชม.'],['22to24','22–24 ชม.'],['24to48','24–48 ชม.'],['over48','>48 ชม.']];
const state={page:'dashboard',bands:new Set(TIME_BANDS.map(([k])=>k)),scheduled:false};
const text=(el)=>String(el?.textContent??'').trim();
const esc=(v)=>String(v??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function clean(v){const raw=String(v??'').trim();return raw.replace(/^\s*(?:(?:\([^)]*\)|（[^）]*）)\s*)+/,'').trim()||raw;}
function parseTime(v){const raw=String(v??'').trim();if(!raw||raw==='-'||raw==='--')return NaN;let s=raw;if(/^\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}/.test(raw)&&!/(?:Z|[+-]\d{2}:?\d{2})$/i.test(raw))s=raw.replace(' ','T')+'+07:00';const n=Date.parse(s);return Number.isFinite(n)?n:NaN;}
function bandOf(v,now=Date.now()){const t=parseTime(v);if(!Number.isFinite(t)||now<t)return'unknown';const h=(now-t)/3600000;if(h<3)return'under3';if(h<6)return'3to6';if(h<9)return'6to9';if(h<12)return'9to12';if(h<16)return'12to16';if(h<22)return'16to22';if(h<24)return'22to24';if(h<=48)return'24to48';return'over48';}
function sourceAliases(){const[codePart,...rest]=text($('branch-select')?.selectedOptions?.[0]).split('·');return{code:String(codePart||'').trim().toUpperCase(),name:String(rest.join('·')||'').trim()};}
function normalize(v){return clean(v).toUpperCase().replace(/^\d+\s*/,'').replace(/\s+/g,' ').trim();}
function isOwnHub(v){const raw=clean(v);if(!raw)return false;const{code,name}=sourceAliases();if(name&&normalize(raw)===normalize(name))return true;if(!code)return false;const x=code.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return new RegExp(`(^|[^A-Z0-9])${x}(?:_HUB)?([^A-Z0-9]|$)`,'i').test(raw.toUpperCase());}
function loadBands(){try{const a=JSON.parse(localStorage.getItem('ms-dashboard-time-bands')||'null');if(Array.isArray(a))state.bands=new Set(a.filter((k)=>TIME_BANDS.some(([b])=>b===k)));}catch{}}
function saveBands(){localStorage.setItem('ms-dashboard-time-bands',JSON.stringify([...state.bands]));}
function allBands(){return state.bands.size===TIME_BANDS.length;}
function chosenSet(id){const el=$(id);return new Set(el?[...el.selectedOptions].map(o=>o.value).filter(Boolean):[]);}
function filters(){return{lh:chosenSet('hub-filter'),fd:chosenSet('branch-filter'),action:chosenSet('ops-action-filter'),manager:chosenSet('manager-phone-filter')};}
function fullData(){const d=window.__MS_FULL_ANALYTICS;return d?.complete&&Array.isArray(d.cells)?d:null;}
function fullCells({ignoreTime=false}={}){const d=fullData();if(!d)return[];const f=filters();return d.cells.filter((c)=>{if(!ignoreTime&&!allBands()&&!state.bands.has(c.b))return false;if(f.lh.size&&(c.r!=='lh'||!f.lh.has(c.d)))return false;if(f.fd.size&&(c.r!=='fd'||!f.fd.has(c.d)))return false;if(f.action.size&&!f.action.has(c.a))return false;if(f.manager.size&&!f.manager.has(String(c.m||'-')))return false;return true;});}
function metrics(cells){return cells.reduce((m,c)=>{m.count+=Number(c.c||0);m.bagged+=Number(c.g||0);m.overdue+=Number(c.o||0);m.critical+=Number(c.q||0);return m;},{count:0,bagged:0,overdue:0,critical:0});}
function aggregate(cells,keyFn){const map=new Map();for(const c of cells){const k=String(keyFn(c)||'-');map.set(k,(map.get(k)||0)+Number(c.c||0));}return[...map.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0],'th'));}
function renderList(id,entries,total,max=12){const el=$(id);if(!el)return;const rows=entries.slice(0,max);el.innerHTML=rows.length?rows.map(([name,count])=>`<div class="summary-row"><div><span>${esc(name)}</span><strong>${fmt.format(count)}</strong></div><i><b style="width:${total?Math.max(3,Math.round(count/total*100)):0}%"></b></i></div>`).join(''):'<div class="summary-empty">-</div>';}
function parseDomRows(){return[...document.querySelectorAll('#table-body tr')].map((tr)=>{const c=tr.cells;return{pno:text(c[0]),state_name:text(c[1]),plan_leave_time:text(c[4]?.querySelector('.cell-stack > span')),real_arrive_time:text(c[4]?.querySelector('.cell-stack > small')),pack_num:text(c[5]),LastAction_name:text(c[7]?.querySelector('.cell-stack > span'))||'-',LastActionTime:text(c[7]?.querySelector('.cell-stack > small')),store_manager_phone:'-',dst_hub_name:text(c[9]?.querySelector('.cell-stack > span')),dst_store_name:text(c[9]?.querySelector('.cell-stack > small'))};}).filter((r)=>r.pno);}
function rowMatch(r){const f=filters();const b=bandOf(r.LastActionTime);if(!allBands()&&!state.bands.has(b))return false;const hub=clean(r.dst_hub_name),fd=clean(r.dst_store_name),own=isOwnHub(r.dst_hub_name);if(f.lh.size&&(own||!f.lh.has(hub)))return false;if(f.fd.size&&(!own||!f.fd.has(fd)))return false;if(f.action.size&&!f.action.has(String(r.LastAction_name||'-')))return false;if(f.manager.size&&!f.manager.has(String(r.store_manager_display||r.store_manager_phone||'-')))return false;return true;}
function bandLabel(k){return k==='unknown'?'อายุไม่ทราบ':TIME_BANDS.find(([x])=>x===k)?.[1]||k;}
function updateTimeUI(){document.querySelectorAll('[data-dashboard-band]').forEach((el)=>{el.checked=state.bands.has(el.dataset.dashboardBand);});const labels=TIME_BANDS.filter(([k])=>state.bands.has(k)).map(([,l])=>l);const s=allBands()?'ทั้งหมด':labels.length?labels.join(' + '):'ไม่ได้เลือก';if($('dashboard-time-selected'))$('dashboard-time-selected').textContent=s;if($('backlog-time-label'))$('backlog-time-label').textContent=s;}
function renderDashboard(){const d=fullData();if(d){const cells=fullCells(),m=metrics(cells),base=fullCells({ignoreTime:true}),bandMap=new Map(TIME_BANDS.map(([k])=>[k,0]));for(const c of base)if(bandMap.has(c.b))bandMap.set(c.b,(bandMap.get(c.b)||0)+Number(c.c||0));document.querySelectorAll('[data-band-count]').forEach((el)=>el.textContent=fmt.format(bandMap.get(el.dataset.bandCount)||0));$('dash-loaded').textContent=fmt.format(Number(d.total||0));$('dash-selected').textContent=fmt.format(m.count);$('dash-over-plan').textContent=fmt.format(m.overdue);$('dash-bagged').textContent=fmt.format(m.bagged);$('dash-critical').textContent=fmt.format(m.critical);$('dashboard-selection-note').textContent=`${fmt.format(m.count)} / ${fmt.format(Number(d.total||0))} รายการ`;renderList('dashboard-time-summary',TIME_BANDS.map(([k,l])=>[l,bandMap.get(k)||0]),base.reduce((s,c)=>s+Number(c.c||0),0),9);renderList('dashboard-hub-summary',aggregate(cells.filter((c)=>c.r==='lh'),(c)=>c.d),m.count);renderList('dashboard-branch-summary',aggregate(cells.filter((c)=>c.r==='fd'),(c)=>c.d),m.count);renderList('dashboard-action-summary',aggregate(cells,(c)=>c.a),m.count);updateTimeUI();return;}
  const rows=parseDomRows(),selected=rows.filter(rowMatch),bandMap=new Map(TIME_BANDS.map(([k])=>[k,0]));for(const r of rows){const b=bandOf(r.LastActionTime);if(bandMap.has(b))bandMap.set(b,(bandMap.get(b)||0)+1);}document.querySelectorAll('[data-band-count]').forEach((el)=>el.textContent=fmt.format(bandMap.get(el.dataset.bandCount)||0));$('dash-loaded').textContent=text($('m-total'))||'0';$('dash-selected').textContent=fmt.format(selected.length);$('dash-over-plan').textContent='-';$('dash-bagged').textContent=fmt.format(selected.filter((r)=>r.pack_num&&r.pack_num!=='-').length);$('dash-critical').textContent='-';$('dashboard-selection-note').textContent=selected.length?`${fmt.format(selected.length)} รายการในหน้าปัจจุบัน`:'-';updateTimeUI();}
async function fullRowsForCopy(){try{if(!window.MSFullSnapshot)await import('./snapshot-client.js?v=20260906-1');return await window.MSFullSnapshot?.ensureLoaded?.()||[];}catch{return[];}}
async function copySelected(){const status=$('dashboard-copy-status');if(status)status.textContent='กำลังเตรียมรายการ…';let rows=await fullRowsForCopy();if(!rows.length)rows=parseDomRows();rows=rows.filter(rowMatch);if(!rows.length){if(status)status.textContent='ไม่มีรายการ';return;}const lines=[`MS Parcel Live · ${text($('branch-select')?.selectedOptions?.[0])||'-'}`,`รวม ${fmt.format(rows.length)} รายการ`,...rows.map((r,i)=>`${i+1}. ${r.pno} | ${bandLabel(bandOf(r.LastActionTime))} | ${r.LastAction_name||'-'} | แบ็ก ${r.pack_num||'-'} | ${isOwnHub(r.dst_hub_name)?clean(r.dst_store_name):clean(r.dst_hub_name)}`)];try{await navigator.clipboard.writeText(lines.join('\n'));if(status)status.textContent=`คัดลอก ${fmt.format(rows.length)} เลขพัสดุแล้ว`;}catch{if(status)status.textContent='คัดลอกไม่สำเร็จ';}}
function applyDomBandFilter(){const active=state.page!=='dashboard'&&!allBands(),rows=parseDomRows();rows.forEach((r)=>r.tr?.classList?.toggle('dashboard-time-hidden',active&&!state.bands.has(bandOf(r.LastActionTime))));$('backlog-time-banner')?.classList.toggle('hidden',!(state.page==='backlog'&&active));}
function setPage(next,{hash=true}={}){const page=PAGE_IDS.has(next)?next:'dashboard',target=document.querySelector(`[data-page-view="${page}"]`);if(!target){setTimeout(()=>setPage(page,{hash}),100);return;}state.page=page;document.querySelectorAll('[data-page-view]').forEach((s)=>s.classList.toggle('hidden',s.dataset.pageView!==page));document.querySelectorAll('[data-page-nav]').forEach((b)=>b.classList.toggle('active',b.dataset.pageNav===page));const panel=$('results-panel'),slot=page==='parcels'?$('parcels-results-slot'):page==='backlog'?$('backlog-results-slot'):null;if(panel&&slot&&panel.parentElement!==slot)slot.appendChild(panel);if(hash&&location.hash!==`#${page}`)history.replaceState(null,'',`#${page}`);applyDomBandFilter();renderDashboard();window.dispatchEvent(new CustomEvent('ms-page-change',{detail:{page}}));window.scrollTo({top:0,behavior:'auto'});}
function schedule(){if(state.scheduled)return;state.scheduled=true;requestAnimationFrame(()=>{state.scheduled=false;try{renderDashboard();applyDomBandFilter();}catch(e){console.error('[shell]',e);}});}
function bind(){document.querySelectorAll('[data-page-nav]').forEach((b)=>b.addEventListener('click',()=>setPage(b.dataset.pageNav)));window.addEventListener('hashchange',()=>setPage(location.hash.slice(1),{hash:false}));document.querySelectorAll('[data-dashboard-band]').forEach((el)=>el.addEventListener('change',()=>{const k=el.dataset.dashboardBand;if(el.checked)state.bands.add(k);else state.bands.delete(k);saveBands();schedule();}));$('dashboard-time-all')?.addEventListener('click',()=>{state.bands=new Set(TIME_BANDS.map(([k])=>k));saveBands();schedule();});$('dashboard-time-clear')?.addEventListener('click',()=>{state.bands.clear();saveBands();schedule();});$('backlog-time-clear')?.addEventListener('click',()=>{state.bands=new Set(TIME_BANDS.map(([k])=>k));saveBands();schedule();});$('dashboard-copy-selected')?.addEventListener('click',(e)=>{e.stopImmediatePropagation();void copySelected();},{capture:true});$('dashboard-open-selected')?.addEventListener('click',()=>setPage('backlog'));document.addEventListener('change',(e)=>{if(['hub-filter','branch-filter','ops-action-filter','manager-phone-filter'].includes(e.target?.id))setTimeout(schedule,0);});window.addEventListener('ms-full-analytics',schedule);window.addEventListener('ms-ops-ready',()=>{if(['status','weight'].includes(state.page))setPage(state.page,{hash:false});});}
function init(){loadBands();bind();const tbody=$('table-body');if(tbody)new MutationObserver(schedule).observe(tbody,{childList:true});setPage(PAGE_IDS.has(location.hash.slice(1))?location.hash.slice(1):'dashboard',{hash:true});renderDashboard();window.__MS_NAV_READY=true;setTimeout(()=>import('./analytics-client.js?v=20260906-3').catch(()=>{}),0);setInterval(()=>{if(!document.hidden)schedule();},60000);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();