import {createRequire} from 'node:module';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {strict as assert} from 'node:assert';
import * as model from './data-model.js';
const require=createRequire(import.meta.url);const {JSDOM}=require('jsdom');
const dom=new JSDOM(readFileSync('index.html','utf8'),{url:'https://example.test/',runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window;Object.assign(w,model);w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};
let clipboard='';Object.defineProperty(w.navigator,'clipboard',{value:{writeText:async t=>{clipboard=t}}});w.setInterval=()=>0;
let queue=[];w.requestAnimationFrame=cb=>{queue.push(cb);return queue.length};const flush=()=>{while(queue.length)queue.shift()()};
let loaded=false;
const M1='(TH00000001)01 TEST_HUB-A · นาย ผู้จัดการ เอ · 0811111111';
const M2='(TH00000002)02 TEST_HUB-B · นางสาว ผู้จัดการ บี · 0822222222';
const fixtures=[{pno:'P001',dst_hub_name:'NE1_HUB',dst_store_name:'A',store_manager_display:M1,store_id:'TH00000001',store_name:'01 TEST_HUB-A',store_manager_name:'นาย ผู้จัดการ เอ',store_manager_phone:'0811111111',staff_info_phone:'099',real_arrive_time:'2026-09-03 00:00:00',plan_leave_time:'2026-09-04 00:00:00',pack_num:'B1',LastAction_name:'รับเข้า',LastActionTime:'2026-09-03 00:00:00',state_name:'คงคลัง',store_weight:1000},{pno:'P002',dst_hub_name:'NE4_HUB',dst_store_name:'B',store_manager_display:M2,store_id:'TH00000002',store_name:'02 TEST_HUB-B',store_manager_name:'นางสาว ผู้จัดการ บี',store_manager_phone:'0822222222',real_arrive_time:'2026-09-05 23:00:00',pack_num:'B1',LastAction_name:'คัดแยก',state_name:'คงคลัง',store_weight:2000}];
const emit=(n,d)=>w.dispatchEvent(new w.CustomEvent(n,{detail:d}));
w.MSFullSnapshot={status:()=>({loaded,loadedSnapshotId:'test'}),reset:()=>{loaded=false},ensureLoaded:async()=>{loaded=true;emit('ms-full-rows',{rows:fixtures,snapshotId:'test',branchId:1,total:2});return fixtures}};
const code=readFileSync('ops.js','utf8').split('\n').filter(l=>!l.startsWith('import ')).join('\n');vm.runInContext(code,dom.getInternalVMContext());flush();
assert.match(w.document.querySelector('#work-dashboard').textContent,/รอภาพรวม/);
emit('ms-branch-ready',{id:1,code:'NE1',name:'NE1_HUB'});
const a={branchId:1,schemaVersion:8,complete:true,total:2,scanned:2,snapshotId:'test',snapshotStore:'live_cache_pages',snapshotPages:1,snapshotExpiresAt:'2099-01-01',updatedAt:'2026-09-06T00:00:00+07:00',fd:[{name:'A'}],lh:[{name:'NE4_HUB'}],actions:[{name:'รับเข้า'},{name:'คัดแยก'}],managerPhones:[{name:M1},{name:M2}],cells:[{r:'fd',d:'A',b:'over48',a:'รับเข้า',m:M1,c:1,w:1,g:1,o:1,q:1},{r:'lh',d:'NE4_HUB',b:'under3',a:'คัดแยก',m:M2,c:1,w:2,g:1,o:0,q:0}]};
emit('ms-full-analytics',a);flush();assert.equal(w.document.querySelectorAll('.work-kpi').length,4);assert.match(w.document.querySelector('#work-dashboard').textContent,/ปลายทางที่ต้องติดตาม/);assert.match(w.document.querySelector('#work-dashboard').textContent,/ผู้จัดการ เอ/);
const managerOptions=[...w.document.querySelector('#manager-phone-filter').options].map(o=>o.textContent);assert.ok(managerOptions.some(v=>v.includes('TEST_HUB-A')&&v.includes('ผู้จัดการ เอ')&&v.includes('0811111111')));
const nav=id=>{w.document.querySelector(`[data-page-nav="${id}"]`).click();flush()};
nav('status');assert.equal(w.document.querySelectorAll('.work-charts .work-panel').length,3);
nav('weight');assert.match(w.document.querySelector('#work-weight').textContent,/เฉลี่ย/);
nav('parcels');await new Promise(r=>setTimeout(r,0));flush();assert.equal(w.document.querySelectorAll('.parcel-row').length,2);assert.match(w.document.querySelector('#work-parcels').textContent,/ผู้จัดการ เอ/);
w.document.querySelector('.parcel-row').click();assert.equal(w.document.querySelector('#parcel-dialog').open,true);assert.match(w.document.querySelector('#parcel-detail').textContent,/TEST_HUB-A/);assert.match(w.document.querySelector('#parcel-detail').textContent,/0811111111/);w.document.querySelector('#close-parcel').click();
const mgr=w.document.querySelector('#manager-phone-filter');mgr.value=M1;mgr.dispatchEvent(new w.Event('change'));flush();assert.equal(w.document.querySelectorAll('.parcel-row').length,1);
await vm.runInContext("copy('list')",dom.getInternalVMContext());assert.match(clipboard,/P001/);assert.doesNotMatch(clipboard,/P002/);mgr.value='';mgr.dispatchEvent(new w.Event('change'));flush();
nav('bagging');await new Promise(r=>setTimeout(r,0));flush();assert.match(w.document.querySelector('#work-bagging').textContent,/ปลายทางปน/);assert.equal(w.document.querySelectorAll('.work-bag').length,1);
await vm.runInContext("copy('bags')",dom.getInternalVMContext());assert.match(clipboard,/P001/);assert.match(clipboard,/P002/);
nav('backlog');await new Promise(r=>setTimeout(r,0));w.document.querySelector('[data-work-risk="over48"]').click();flush();assert.equal(w.document.querySelectorAll('#work-backlog .parcel-row').length,1);
await vm.runInContext("copy('list')",dom.getInternalVMContext());assert.doesNotMatch(clipboard,/P002/);
emit('ms-full-analytics',{...a,complete:false,total:3,scanned:2,snapshotId:null});flush();nav('dashboard');assert.match(w.document.querySelector('#work-dashboard').textContent,/ข้อมูลบางส่วน/);const beforeCopy=clipboard;await vm.runInContext("copy('dashboard')",dom.getInternalVMContext());assert.equal(clipboard,beforeCopy);nav('backlog');emit('ms-session-reset');flush();assert.match(w.document.querySelector('#work-backlog').textContent,/รอภาพรวม/);assert.equal(w.document.querySelector('#parcel-detail').textContent,'');
console.log('PASS: six views, no partial fallback, full manager column filter/display, FD/LH charts and weights, mixed bag, details, copy and logout clearing');
